### ISSUE TITLE
Error: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by guohengkai** [colmap/pycolmap#100]
Hi, 
When I'm trying to load the reconstruction of ETH3D datasets, I found some strange errors like:
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(i, len(image.points2D))
RecursionError: maximum recursion depth exceeded while calling a Python object

Example codes:

import pycolmap

reference_sfm = 'test'
rec_ref = pycolmap.Reconstruction(reference_sfm)

for i, image in rec_ref.images.items():
    print(i, len(image.points2D))

I have tried the pull request #95 , but it doesn't work.

Colmap commit id: b016aed098
Ceres commit id: f68321e7de (2.1.0)

**Comment by sarlinpe** [comment]
I cannot reproduce this locally at HEAD.
