### ISSUE TITLE
how to use user-define keypoint and correspondcane to estimate?

### ISSUE THREAD

**Issue by Talegqz** [colmap/pycolmap#101]
I have dense correspondence of images, and I want to use it to reconstruct instead of SIFT or others.
Does colmap have interface to do that?
Thank you for your reply.

**Comment by sarlinpe** [comment]
COLMAP assumes to have correspondences between keypoints. Using pair-wise dense correspondences requires clustering them into tracks. See [`hloc/match_dense.py`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py) for an example on how to do this, [with the corresponding pipeline](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py).
