### ISSUE TITLE
ERROR: Failed building wheel for pycolmap [Ubuntu 18.04.6] 

### ISSUE THREAD

**Issue by Mehi44** [colmap/pycolmap#103]
I get the following error when trying to install using `pip install git+https://github.com/colmap/pycolmap` 

$ pip install git+https://github.com/colmap/pycolmap
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/colmap/pycolmap
  Cloning https://github.com/colmap/pycolmap to /tmp/pip-req-build-jgv4y16i
  Running command git clone --filter=blob:none -q https://github.com/colmap/pycolmap /tmp/pip-req-build-jgv4y16i
  Resolved https://github.com/colmap/pycolmap to commit 391a1c28110fd6c61b4c6550e1e19bc4295398a5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5d8s86au
       cwd: /tmp/pip-req-build-jgv4y16i/
  Complete output (141 lines):
  running bdist_wheel
  running build
  running build_ext
  ['cmake', '/tmp/pip-req-build-jgv4y16i', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-jgv4y16i/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DVERSION_INFO=0.4.0', '-DCMAKE_BUILD_TYPE=Release']
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found CXSparse: /usr/include/suitesparse (found suitable version "3.1.9", minimum required is "3.1.9")
  -- A library with BLAS API found.
  -- Found AMD headers in: /usr/include/suitesparse
  -- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
  -- Found CAMD headers in: /usr/include/suitesparse
  -- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
  -- Found CCOLAMD headers in: /usr/include/suitesparse
  -- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
  -- Found CHOLMOD headers in: /usr/include/suitesparse
  -- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
  -- Found COLAMD headers in: /usr/include/suitesparse
  -- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
  -- Found SPQR headers in: /usr/include/suitesparse
  -- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
  -- Found Config headers in: /usr/include/suitesparse
  -- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
  -- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
  -- Looking for shm_open in rt
  -- Looking for shm_open in rt - found
  -- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
  -- Found METIS: /usr/include (found version "5.1.0")
  -- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.1.2", minimum required is "5.1.2") found components:  AMD CAMD CCOLAMD CHOLMOD COLAMD SPQR Config
  -- Found required Ceres dependency: Eigen version 3.3.4 in /usr/lib/cmake/eigen3
  -- Found required Ceres dependency: glog
  -- Found required Ceres dependency: gflags
  -- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
  -- Boost version: 1.65.1
  -- Found the following Boost libraries:
  --   program_options
  --   filesystem
  --   system
  --   unit_test_framework
  -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
  -- Found Eigen
  --   Includes : /usr/include/eigen3
  -- Found FreeImage
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
  -- Found Glog
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
  -- Found Glew
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
  -- pybind11 v2.8.1
  -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  Compiling bindings with CUDA support.
  -- Configuring done
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      VERSION_INFO
  
  
  -- Build files have been written to: /tmp/pip-req-build-jgv4y16i/build/temp.linux-x86_64-3.6
  Scanning dependencies of target pycolmap
  [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
  In file included from /tmp/pip-req-build-jgv4y16i/main.cc:9:0:
  /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc: In function ‘pybind11::dict absolute_pose_estimation(std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, colmap::Camera&, colmap::AbsolutePoseEstimationOptions, colmap::AbsolutePoseRefinementOptions, bool)’:
  /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc:53:70: error: too many arguments to function ‘bool colmap::RefineAbsolutePose(const colmap::AbsolutePoseRefinementOptions&, const std::vector<char>&, const std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > >&, const std::vector<Eigen::Matrix<double, 3, 1> >&, Eigen::Vector4d*, Eigen::Vector3d*, colmap::Camera*)’
                               return_covariance ? &covariance : nullptr)) {
                                                                        ^
  In file included from /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc:7:0,
                   from /tmp/pip-req-build-jgv4y16i/main.cc:9:
  /usr/local/include/colmap/estimators/pose.h:164:6: note: declared here
   bool RefineAbsolutePose(const AbsolutePoseRefinementOptions& options,
        ^~~~~~~~~~~~~~~~~~
  In file included from /tmp/pip-req-build-jgv4y16i/main.cc:10:0:
  /tmp/pip-req-build-jgv4y16i/estimators/generalized_absolute_pose.cc: In function ‘pybind11::dict rig_absolute_pose_estimation(std::vector<std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > > >, std::vector<std::vector<Eigen::Matrix<double, 3, 1> > >, std::vector<colmap::Camera>, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, colmap::RANSACOptions, colmap::AbsolutePoseRefinementOptions, bool)’:
  /tmp/pip-req-build-jgv4y16i/estimators/generalized_absolute_pose.cc:195:10: error: ‘RefineGeneralizedAbsolutePose’ was not declared in this scope
       if (!RefineGeneralizedAbsolutePose(
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CMakeFiles/pycolmap.dir/build.make:62: recipe for target 'CMakeFiles/pycolmap.dir/main.cc.o' failed
  make[2]: *** [CMakeFiles/pycolmap.dir/main.cc.o] Error 1
  CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pycolmap.dir/all' failed
  make[1]: *** [CMakeFiles/pycolmap.dir/all] Error 2
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-jgv4y16i/setup.py", line 93, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-jgv4y16i/setup.py", line 35, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-jgv4y16i/setup.py", line 78, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for pycolmap
  Running setup.py clean for pycolmap
Failed to build pycolmap
Installing collected packages: pycolmap
  Attempting uninstall: pycolmap
    Found existing installation: pycolmap 0.3.0
    Uninstalling pycolmap-0.3.0:
      Successfully uninstalled pycolmap-0.3.0
    Running setup.py install for pycolmap ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kpbwgatd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mehi/.local/include/python3.6m/pycolmap
         cwd: /tmp/pip-req-build-jgv4y16i/
    Complete output (143 lines):
    running install
    running build
    running build_ext
    ['cmake', '/tmp/pip-req-build-jgv4y16i', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-jgv4y16i/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DVERSION_INFO=0.4.0', '-DCMAKE_BUILD_TYPE=Release']
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found CXSparse: /usr/include/suitesparse (found suitable version "3.1.9", minimum required is "3.1.9")
    -- A library with BLAS API found.
    -- Found AMD headers in: /usr/include/suitesparse
    -- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
    -- Found CAMD headers in: /usr/include/suitesparse
    -- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
    -- Found CCOLAMD headers in: /usr/include/suitesparse
    -- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
    -- Found CHOLMOD headers in: /usr/include/suitesparse
    -- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
    -- Found COLAMD headers in: /usr/include/suitesparse
    -- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
    -- Found SPQR headers in: /usr/include/suitesparse
    -- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
    -- Found Config headers in: /usr/include/suitesparse
    -- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
    -- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
    -- Looking for shm_open in rt
    -- Looking for shm_open in rt - found
    -- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
    -- Found METIS: /usr/include (found version "5.1.0")
    -- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.1.2", minimum required is "5.1.2") found components:  AMD CAMD CCOLAMD CHOLMOD COLAMD SPQR Config
    -- Found required Ceres dependency: Eigen version 3.3.4 in /usr/lib/cmake/eigen3
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
    -- Boost version: 1.65.1
    -- Found the following Boost libraries:
    --   program_options
    --   filesystem
    --   system
    --   unit_test_framework
    -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
    -- Found Eigen
    --   Includes : /usr/include/eigen3
    -- Found FreeImage
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
    -- Found Glog
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
    -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    -- Found Glew
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
    -- pybind11 v2.8.1
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    Compiling bindings with CUDA support.
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        VERSION_INFO
    
    
    -- Build files have been written to: /tmp/pip-req-build-jgv4y16i/build/temp.linux-x86_64-3.6
    Scanning dependencies of target pycolmap
    [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
    In file included from /tmp/pip-req-build-jgv4y16i/main.cc:9:0:
    /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc: In function ‘pybind11::dict absolute_pose_estimation(std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, colmap::Camera&, colmap::AbsolutePoseEstimationOptions, colmap::AbsolutePoseRefinementOptions, bool)’:
    /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc:53:70: error: too many arguments to function ‘bool colmap::RefineAbsolutePose(const colmap::AbsolutePoseRefinementOptions&, const std::vector<char>&, const std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > >&, const std::vector<Eigen::Matrix<double, 3, 1> >&, Eigen::Vector4d*, Eigen::Vector3d*, colmap::Camera*)’
                                 return_covariance ? &covariance : nullptr)) {
                                                                          ^
    In file included from /tmp/pip-req-build-jgv4y16i/estimators/absolute_pose.cc:7:0,
                     from /tmp/pip-req-build-jgv4y16i/main.cc:9:
    /usr/local/include/colmap/estimators/pose.h:164:6: note: declared here
     bool RefineAbsolutePose(const AbsolutePoseRefinementOptions& options,
          ^~~~~~~~~~~~~~~~~~
    In file included from /tmp/pip-req-build-jgv4y16i/main.cc:10:0:
    /tmp/pip-req-build-jgv4y16i/estimators/generalized_absolute_pose.cc: In function ‘pybind11::dict rig_absolute_pose_estimation(std::vector<std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > > >, std::vector<std::vector<Eigen::Matrix<double, 3, 1> > >, std::vector<colmap::Camera>, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, colmap::RANSACOptions, colmap::AbsolutePoseRefinementOptions, bool)’:
    /tmp/pip-req-build-jgv4y16i/estimators/generalized_absolute_pose.cc:195:10: error: ‘RefineGeneralizedAbsolutePose’ was not declared in this scope
         if (!RefineGeneralizedAbsolutePose(
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CMakeFiles/pycolmap.dir/build.make:62: recipe for target 'CMakeFiles/pycolmap.dir/main.cc.o' failed
    make[2]: *** [CMakeFiles/pycolmap.dir/main.cc.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pycolmap.dir/all' failed
    make[1]: *** [CMakeFiles/pycolmap.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-jgv4y16i/setup.py", line 93, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-jgv4y16i/setup.py", line 35, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-jgv4y16i/setup.py", line 78, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
  Rolling back uninstall of pycolmap
  Moving to /home/mehi/.local/lib/python3.6/site-packages/pycolmap-0.3.0.dist-info/
   from /home/mehi/.local/lib/python3.6/site-packages/~ycolmap-0.3.0.dist-info
  Moving to /home/mehi/.local/lib/python3.6/site-packages/pycolmap.cpython-36m-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-qkw4v83k/pycolmap.cpython-36m-x86_64-linux-gnu.so
  Moving to /home/mehi/.local/lib/python3.6/site-packages/pycolmap.libs/
   from /home/mehi/.local/lib/python3.6/site-packages/~ycolmap.libs
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jgv4y16i/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kpbwgatd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mehi/.local/include/python3.6m/pycolmap Check the logs for full command output.

**Comment by Skydes** [comment]
How did you install COLMAP? pycolmap requires a recent install of COLMAP - currently at least commit https://github.com/colmap/colmap/commit/33e26924f950172751f044a89b964129b3728db8 dated 17/03/2022.

@mihaidusmanu We should include in the README a link to the oldest COLMAP commit admissible.

**Comment by mihaidusmanu** [comment]
Will be fixed in #112
