### ISSUE TITLE
ImportError libfreeimage.so.3: symbol _TIFFDataSize, version LIBTIFF_4.0 not defined in file libtiff.so.5 with link time reference

### ISSUE THREAD

**Issue by JzHuai0108** [colmap/pycolmap#105]
I have successfully built and installed colmap, pyceres, pycolmap on centos 7.
For pycolmap, this can be verified by pip show pycolmap.
However, when I import pycolmap, an error about libfreeimage.so shows up.
```
$ python3
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libfreeimage.so.3: symbol _TIFFDataSize, version LIBTIFF_4.0 not defined in file libtiff.so.5 with link time reference
```
I understand that colmap depends on libfreeimage.so. The situation looks like libtiff.so is not found.
So I browsed the system, finding out all the libtiff.so as listed below.
```
(base) [huaijianzhu@swarm03 anaconda3]$ find . -name "*libtiff.so*"
./pkgs/libtiff-4.4.0-hecacb30_0/lib/libtiff.so.5
./pkgs/libtiff-4.4.0-hecacb30_0/lib/libtiff.so.5.8.0
./pkgs/libtiff-4.4.0-hecacb30_0/lib/libtiff.so
./lib/libtiff.so.5
./lib/libtiff.so.5.8.0
./lib/libtiff.so
(base) [huaijianzhu@swarm03 anaconda3]$ cd /usr/
(base) [huaijianzhu@swarm03 usr]$ find . -name "libtiff.so*"
./lib64/libtiff.so.5
./lib64/libtiff.so.5.2.0
./lib64/libtiff.so
find: ‘./libexec/initscripts/legacy-actions/auditd’: Permission denied
find: ‘./share/polkit-1/rules.d’: Permission denied
(base) [huaijianzhu@swarm03 usr]$ cd /lib64
(base) [huaijianzhu@swarm03 lib64]$ find . -name "libtiff.so*"
./libtiff.so.5
./libtiff.so.5.2.0
./libtiff.so
```

The current LD_LIBRARY_PATH is 
```
$ echo $LD_LIBRARY_PATH
/software/nvidia/cuda/10.2/lib64:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst
```
I tried to add one of these above paths to LD_LIBRARY_PATH by export, e.g., export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64.
But none of them worked.

Do you have a clue on how to resolve this issue?

**Comment by JzHuai0108** [comment]
After several hours of dogged effort, it pulls off.
The issue is again not new and the answer is again simple as given [here](https://github.com/colmap/colmap/issues/188).
For the curious and my future self, here are the details.
First, I removed the conflicting anaconda libtiff by
```
conda uninstall libtiff
```
After this, I realized that that operation almost removed all packages from anaconda 3. But I guess this is fine as long as anaconda is consistent.
Then I built and installed pycolmap again,
```
cd pycolmap
pip install .
```
No way, missing packages:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hloc 1.3 requires h5py, which is not installed.
hloc 1.3 requires matplotlib, which is not installed.
hloc 1.3 requires numpy, which is not installed.
hloc 1.3 requires plotly, which is not installed.
hloc 1.3 requires scipy, which is not installed
```
So I installed these packages by pip,
```
pip3 install h5py numpy matplotlib plotly scipy
```
Note that the anaconda paths are intact in my ~/.bashrc, so the above packages were installed into anaconda3.

Finally, I rebuilt and reinstalled pycolmap successfully by
```
cd pycolmap
pip install .
python
import pycolmap
```

**Comment by SimonStrassen97** [comment]
The **conda uninstall libtiff** worked for me too. The problem though is you can not use spyder anymore within the same environment: when you reinstall spyder in the environment the pycolmap import error returns.
So I just switched to VS code

**Comment by MTshengyi** [comment]
Same problem. I find that after 'conda uninstall libtiff', the pycolmap could install. However, when you install torch and/or opencv-python in conda env, libtiff would also re-install. Therefore, the error happen again. 
I try mangy solutions (eg. [methods mentioned in Issues](https://github.com/colmap/colmap/issues/188), modify CMake files of both colmap and pycolmap), but none of these work.
Finally, I find that just don't use conda, and turn to pure python (‘apt-get install python3.8’), that works to me!

**Comment by yyyyyyyllllll** [comment]
Similar issue here with conda on Ubuntu 22.04.

The error log I got was 
`libfreeimage.so.3: undefined symbol: _TIFFDataSize, version LIBTIFF_4.0` and this bug was reported in https://bugs.launchpad.net/savos/+bug/1979176. 

Adding ppa and upgrading the libs work for me.
```
add-apt-repository ppa:savoury1/graphic
apt update
apt install libfreeimage
```
