### ISSUE TITLE
wheels for python 3.10 pretty please?

### ISSUE THREAD

**Issue by pwais** [colmap/pycolmap#111]
When i try to `pip install pycolmap` with python 3.10 i get "No matching distribution found for pycolmap"

Looking at the files on pypi, it looks like there's just no wheel yet for 3.10:
https://pypi.org/project/pycolmap/#files

But it seems wheel building for 3.10 was added here: https://github.com/colmap/pycolmap/pull/109

Maybe the wheels are pushed manually to pypi?  I think it's all write-once so you have to be careful with releases... 

@johnnynunez since you authored the 3.10 update, do you happen to have permission to publish wheels to pypi?

**Comment by Skydes** [comment]
For this we'll need to push a new release. In the meantime, are you able to download them from the CI ?

**Comment by pwais** [comment]
thanks @Skydes for the quick response! yeah i hear you about needing to just wait for next release.  

ohh interesting, i see so CI preserves all wheels for every PR it seems, e.g. for the latest run (at time of writing)
 * https://github.com/colmap/pycolmap/actions/runs/4161103130 

thank you! yes this is a good stopgap.  hope lazyweb finds this solution as well.

**Comment by johnnynunez** [comment]
I’m trying to do for windows CI with similar strategies but it’s more complicated.

**Comment by pwais** [comment]
ah ok thanks @johnnynunez ! i m on linux / docker FWIW. i got local compile to work so im certainly unblocked for now, but would love to hear if / when wheels are released for python 3.10.  Cool to know the CI keeps the wheels up for public use.

**Comment by johnnynunez** [comment]
> ah ok thanks @johnnynunez ! i m on linux / docker FWIW. i got local compile to work so im certainly unblocked for now, but would love to hear if / when wheels are released for python 3.10. Cool to know the CI keeps the wheels up for public use.

when they publish a release, it's upload automatically on pypi

**Comment by pwais** [comment]
@Skydes Thank you so much!!  So this does help, although as I went further down the rabbit hole, it turns out I needed Windows wheels, and that appears to require COLMAP for Windows ... https://github.com/colmap/pycolmap/pull/114   

Is it a longshot to think perhaps the COLMAP folks might just build / include pycolmap in their own release system?

**Comment by pwais** [comment]
cc https://github.com/nerfstudio-project/nerfstudio/pull/2113  Nerfstudio has moved to pycolmap 0.4.0 at least for development, but windows install is still very manual ( https://github.com/colmap/pycolmap/issues/34#issuecomment-1562449270 )

**Comment by pwais** [comment]
Closing this since:
 * wheels for linux are now available
 * @Skydes says ( https://github.com/nerfstudio-project/nerfstudio/pull/2199 )  pycolmap is trying to track the dev branch of COLMAP, so perhaps a synchronized release of COLMAP + pycolmap for both linux and windows is forthcoming

**Comment by sarlinpe** [comment]
We now have [instructions to build PyCOLMAP on Windows](https://github.com/colmap/pycolmap/tree/sarlinpe/windows-ci#building-from-source). We also have pre-built wheels that are available [here](https://github.com/colmap/pycolmap/actions/runs/7286946343) and can be installed with pip. I don't have a Windows machine at hand so it'd be great if someone could confirm that they work. We'll then release them on PyPI.
