### ISSUE TITLE
failed to run pycolmap.incremental_mapping: F20230221 11:49:22.759709 1251534 bundle_adjustment.cc:304] Check failed: solver_options.IsValid(&solver_error) Invalid configuration. Solver::Options::eta = 0. Violated constraint: Solver::Options::eta > 0.0

### ISSUE THREAD

**Issue by hanny-liu** [colmap/pycolmap#115]
Hello, I run pycolmap.incremental_mapping, but it failed, the error shows:
[2023/02/21 11:49:18 hloc INFO] Running 3D reconstruction...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F20230221 11:49:22.759709 1251534 bundle_adjustment.cc:304] Check failed: solver_options.IsValid(&solver_error) Invalid configuration. Solver::Options::eta = 0. Violated constraint: Solver::Options::eta > 0.0
*** Check failure stack trace: ***

How should I do?

**Comment by sarlinpe** [comment]
Here is the check that failed: https://github.com/ceres-solver/ceres-solver/blob/095d483927d26bffc36d1fcc5fe8e2f1ef7da6b0/internal/ceres/solver.cc#L402, for `Solver::Options::eta` defined [here](https://github.com/ceres-solver/ceres-solver/blob/095d483927d26bffc36d1fcc5fe8e2f1ef7da6b0/include/ceres/solver.h#L627). Its default is `1e-1`, COLMAP doesn't modify it, and PyCOLMAP doesn't expose it - so I don't see how it could get this value.

**Comment by hanny-liu** [comment]
我已收到文件，谢谢！
