### ISSUE TITLE
Pycolmap.Reconstruction (reference_model) returns map base error

### ISSUE THREAD

**Issue by fsa4859** [colmap/pycolmap#116]
I am trying to use the Pycolmap. Reconstruction to build a model from existing camera poses. I added the three text files (cameras.txt, images.txt, points3D.txt) where i added the camera poses in images.txt. Running this file returns this issue

 reference = pycolmap.Reconstruction(reference_model)
IndexError: _Map_base::at

any clues on what might be wrong?

**Comment by Skydes** [comment]
This most likely means that one of your text files is malformed. You may alternatively build the model in Python:
```python
rec = pycolmap.Reconstruction()
camera_id = 1  # increment for each new camera
cam1 = pycolmap.Camera(model_name, w, h, params, camera_id)
rec.add_camera(cam1)
image_id = 1  # increment for each new image
im1 = pycolmap.Image(image_name, [], tvec, qvec, camera_id, id=image_id)
rec.add_image(im1)
rec.write("path/")
```
