### ISSUE TITLE
bug in `normalize_qvec`

### ISSUE THREAD

**Issue by mattyusg** [colmap/pycolmap#118]
There seems to be a "typo" here: 

https://github.com/colmap/pycolmap/blob/401f82658cdad1e8b657c77381863f9e261c7c3c/transformations.cc#L153

this calls the `quaternion inverse` instead of the `normalize`. 

p.s.: pycolmap is great :)

**Comment by sarlinpe** [comment]
Good catch, thank you for reporting this. This function has been deprecated in https://github.com/colmap/pycolmap/commit/62414e4904678ffa5212678ac69901ca26b892d2.
