### ISSUE TITLE
pycolmap fails with vocabulary matching

### ISSUE THREAD

**Issue by ducha-aiki** [colmap/pycolmap#127]
I have tried it on Google Colab, Ubuntu machine, Kaggle kernel and Apple M1  -- all the same.

The colmap-gui works well.

To reproduce:

See the [colab](https://colab.research.google.com/drive/1Vp0bpO1vy1bvDl7PXcVPZFynA0AWuyO5?usp=sharing)

Preparation
```python3
!wget http://cmp.felk.cvut.cz/~mishkdmy/wooden_lady_subset.zip
!unzip -o wooden_lady_subset.zip
!wget https://demuc.de/colmap/vocab_tree_flickr100K_words32K.bin
```

Code:
```python3
import cv2
import pycolmap
import os
import matplotlib.pyplot as plt

dirname = 'wooden_lady_subset'
root_dir1 = '.'

os.makedirs(f'{root_dir1}/baseline-reconstructions/sift/', exist_ok=True)
feature_dir = f'{root_dir1}/baseline-reconstructions/sift/features'
database_path = f'{root_dir1}/baseline-reconstructions/sift/colmap.db'
output_path = f'{root_dir1}/baseline-reconstructions/sift/colmap'

image_dir=dirname
img_fnames = sorted([os.path.join(dirname, x) for x in os.listdir(dirname) if '.jpg' in x])
plt.imshow(cv2.cvtColor(cv2.imread(img_fnames[0]), cv2.COLOR_BGR2RGB))

pycolmap.extract_features(database_path, image_dir)
matching_opt= pycolmap.VocabTreeMatchingOptions(
    vocab_tree_path='vocab_tree_flickr100K_words32K.bin')

pycolmap.match_vocabtree(database_path, matching_options=matching_opt)

```

When I run it not in notebook, I get the following crash message:

```
==============================================================================
Vocabulary tree feature matching
==============================================================================

libc++abi: terminating due to uncaught exception of type std::bad_alloc: std::bad_alloc
zsh: abort      ipython
```

Exhaustive matching works well everywhere.

**Comment by Phil26AT** [comment]
Hi @ducha-aiki

This was a bug on our side. A check broke the vocab-tree file. I pushed a fix to branch [fix-vocab-tree-matching](https://github.com/colmap/pycolmap/tree/fix-vocab-tree-matching).

**Comment by ducha-aiki** [comment]
@Phil26AT Thank you! Would it be possible to make a release on pip somewhen soon? The reason I am asking - to try to have pycolmap with vocab matching on Kaggle for IMC2023
https://www.kaggle.com/competitions/image-matching-challenge-2023/overview

**Comment by Phil26AT** [comment]
@ducha-aiki  Yes this is possible, but we have to fix the MacOS CI first. I'll post an update here.

BTW great work with the IMC2023!
