### ISSUE TITLE
`ImportError: /home/projects/pycolmap/pycolmap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5ceres7Problem25SetParameterBlockConstantEPd`

### ISSUE THREAD

**Issue by sohee-zoe** [colmap/pycolmap#129]
`$ pip list`
```
pyceres                  1.0        /home/projects/pyceres
pycolmap                 0.4.0      /home/projects/pycolmap
```
Colmap and Ceres Solver 2.1 are also installed

I got the following error while importing pycolmap. How can I solve this?
```
import pycolmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/projects/pycolmap/pycolmap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5ceres7Problem25SetParameterBlockConstantEPd
```

**Comment by Anni-Ha** [comment]
I am facing the same issue, have you found a solution?

**Comment by EpipolarWagner** [comment]
Yes, same issue with here. I have cere 2.1 installaed An in /usr/local/inlcude/problem.h I can also find the SetParameterBlockConstant header.
Exporting the ld_libary_path of ceres-solver-2.1.0/lib doesn't. what is causing this linker issues?

**Comment by mihaidusmanu** [comment]
I suppose this is because pycolmap is linked against the wrong version of
ceres. Make sure you only have a single version of ceres installed
system-wide.

Are you using precompiled pycolmap or installed from sources? I suggest the
second.

**Comment by Anni-Ha** [comment]
Thanks! You are right, we had two ceres versions installed, and our COLMAP installation had been done with the wrong ceres version. Re-installing COLMAP with ceres 2.1 and then re-installing pycolmap from source solved it.
