### ISSUE TITLE
about the distance unit of the reconstruction result

### ISSUE THREAD

**Issue by feiyangsuo** [colmap/pycolmap#130]
Thanks for your great work!
I followed your [reconstruction pipeline](https://github.com/colmap/pycolmap#reconstruction-pipeline) to reconstruct a dense point cloud. 
Having many points with a 3-D coordinate in it, I'm wondering if the unit (say millimeter, meter) of these coordinates is available somewhere, so that one can know the true size of the reconstruction target.
Or if the unit is ambiguous, what are these values relative to?

**Comment by sarlinpe** [comment]
Structure-from-Motion can only reconstruct the scene up to an unknown scale.
