### ISSUE TITLE
Pycolmap for Mac ARM64 / Apple silicon

### ISSUE THREAD

**Issue by CGCooke** [colmap/pycolmap#132]
Firstly, awesome project.

However, I would like to use it on Apple ARM64.

I will try and update Github Workflow, and any guidance is much appreciated.

**Comment by Skydes** [comment]
Some folks have written in other issues that they successfully managed to build for M1 or M2. I don't have such machine so I cannot verify this myself. GitHub environments don't yet support Mac ARM64 (see https://github.com/actions/runner-images/issues/2187) so we can't really help on this for now.

**Comment by CGCooke** [comment]
Thank you Paul, much appreciated. 

I will try building on my machine.

**Comment by sarlinpe** [comment]
PyCOLMAP compiles fine for arm64 (Apple Silicon) with cross-compilation. We now have wheels for macOS 12 and 13: https://github.com/colmap/pycolmap/actions/runs/7287818922 I don't have an Apple Silicon machine at hand so it'd be great if someone could try them and confirm that they work.

**Comment by sarlinpe** [comment]
Confirmed that the arm64 wheels work.
