### ISSUE TITLE
Is there a ransac operation in `pycolmap.match_exhaustive` or `pycolmap.IncrementalMapperOptions()` ?

### ISSUE THREAD

**Issue by ForcewithMe66** [colmap/pycolmap#137]
Hi, I am reading the demo pipeline you provided in `Readme`.
```
output_path: pathlib.Path
image_dir: pathlib.Path

output_path.mkdir()
mvs_path = output_path / "mvs"
database_path = output_path / "database.db"

pycolmap.extract_features(database_path, image_dir)
pycolmap.match_exhaustive(database_path)
maps = pycolmap.incremental_mapping(database_path, image_dir, output_path)
maps[0].write(output_path)
# dense reconstruction
pycolmap.undistort_images(mvs_path, output_path, image_dir)
pycolmap.patch_match_stereo(mvs_path)  # requires compilation with CUDA
pycolmap.stereo_fusion(mvs_path / "dense.ply", mvs_path)
```

Do you apply for a ransac operation here? If so, where is it? How can I adjust the parameters of ransac? Thank you so much.

Best regards

**Comment by Phil26AT** [comment]
Hi @ForcewithMe66, the demo pipeline uses all default parameters. However, ransac is used extensively in the mapping pipeline. I suggest having a look into the [`IncrementalMapperOptions`](https://github.com/colmap/pycolmap/blob/master/pipeline/sfm.cc#L126-L184) for an extensive list of available options and default parameters. From python, you can also run `help(pycolmap.IncrementalMapperOptions)` for an overview.

**Comment by Skydes** [comment]
We indeed don't have bindings for [`IncrementalMapperOptions.mapper` and `IncrementalMapperOptions.triangulation`](https://github.com/colmap/colmap/blob/bce8f13727960d9aa4a21bc87524ed11f4706f4f/src/colmap/controllers/incremental_mapper.h#L149-L150). We'd need to bind `IncrementalMapper::Options` and `IncrementalTriangulator::Options` and create setters+getters in `IncrementalMapperOptions`. Feel free to give it a shot if you have time.

**Comment by sarlinpe** [comment]
These options are now exposed, since https://github.com/colmap/pycolmap/commit/89ce832326e91a63a1188bdeacc2888f15477cea.
