### ISSUE TITLE
Tutorial or documentation on pycolmap

### ISSUE THREAD

**Issue by jhzgjhzg** [colmap/pycolmap#138]
I hope to use colmap in Python, so I found this project. Where can I find the documentation for this project, or the introduction of its functions/classes

**Comment by Phil26AT** [comment]
Hi @jhzgjhzg, the current repo indeed lacks good documentation. Until we find time to add proper documentation, I suggest having a look into [hloc](https://github.com/cvg/Hierarchical-Localization/tree/master) or [pixsfm](https://github.com/cvg/pixel-perfect-sfm/tree/main). Both projects use pycolmap extensively.

YOu can also try `help(pycolmap.Reconstruction)`, which provides some documentation about functions and classes (a lot of them have useful docstrings and strongly typed parameters).

**Comment by vitalii-p** [comment]
In hloc I got an error during visualization ([viz_3d.plot_reconstruction](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz_3d.py#L152))

`'pycolmap.Image' object has no attribute 'rotmat'`

Seems like they tried to get rotation matrix from the Image object. Could you suggest how to fix such issue?

**Comment by sarlinpe** [comment]
https://github.com/colmap/colmap/pull/2749 adds API docs for PyCOLMAP, available at https://colmap.github.io/pycolmap/index.html
