### ISSUE TITLE
How can I set a random seed?

### ISSUE THREAD

**Issue by ForcewithMe66** [colmap/pycolmap#142]
I am using pycolmap for sfm, but I am getting different results in every rerun. I only use match_exhaustive `incremental_mapping` in pycolmap. Is there a way to set a random seed for pycolmap to reproduce the result? 

I am sorry that I can't find something relative to this in the document.

**Comment by Skydes** [comment]
IIRC @mihaidusmanu looked into this at some point - the seed is set when possible but there are other sources of randomness.

**Comment by ForcewithMe66** [comment]
Hi @Skydes , thank you for your quick reply. 

Here is another issues, Is there a document or note for the meaning of each parameters in `pycolmap.IncrementalMapperOptions()`? It's so unstable in some of my scenes. I want to make it more stable. 

If you think it should be discussed in a new post, please ask to open a new one.

**Comment by ForcewithMe66** [comment]
Here are the parameters I see with `help(IncrementalMapperOptions)`
```
 |  Data descriptors defined here:
 |  
 |  ba_global_function_tolerance
 |  
 |  ba_global_images_freq
 |  
 |  ba_global_images_ratio
 |  
 |  ba_global_max_num_iterations
 |  
 |  ba_global_max_refinement_change
 |  
 |  ba_global_max_refinements
 |  
 |  ba_global_points_freq
 |  
 |  ba_global_points_ratio
 |  
 |  ba_local_function_tolerance
 |  
 |  ba_local_max_num_iterations
 |  
 |  ba_local_max_refinement_change
 |  
 |  ba_local_max_refinements
 |  
 |  ba_local_num_images
 |  
 |  ba_min_num_residuals_for_multi_threading
 |  
 |  ba_refine_extra_params
 |  
 |  ba_refine_focal_length
 |  
 |  ba_refine_principal_point
 |  
 |  extract_colors
 |  
 |  fix_existing_images
 |  
 |  ignore_watermarks
 |  
 |  image_names
 |  
 |  init_image_id1
 |  
 |  init_image_id2
 |  
 |  init_num_trials
 |  
 |  max_extra_param
 |  
 |  max_focal_length_ratio
 |  
 |  max_model_overlap
 |  
 |  max_num_models
 |  
 |  min_focal_length_ratio
 |  
 |  min_model_size
 |  
 |  min_num_matches
 |  
 |  multiple_models
 |  
 |  num_threads
 |  
 |  snapshot_images_freq
 |  
 |  snapshot_path
```

**Comment by Skydes** [comment]
As for all the bindings in pycolmap, the documentation is in the original COLMAP declaration:
https://github.com/colmap/colmap/blob/9eddf2e45b219923660759715e046db090919b84/src/controllers/incremental_mapper.h#L41

**Comment by ForcewithMe66** [comment]
Thank you so much
