### ISSUE TITLE
Undeclared `EIGEN_STL_UMAP` error when building from source

### ISSUE THREAD

**Issue by nnop** [colmap/pycolmap#143]
Hi, guys. I'm building pycolmap from source and met many error of undeclared `EIGEN_STL_UMAP`:
```
/home/nnop/codes/pycolmap/reconstruction/camera.cc:22:22: error: ‘EIGEN_STL_UMAP’ was not declared in this scope; did you mean ‘EIGEN_OS_MAC’?                                                                                    
  22 | PYBIND11_MAKE_OPAQUE(EIGEN_STL_UMAP(colmap::camera_t, colmap::Camera));                                                                                                                                                  
```

I searched the source code of colmap and Eigen and didn't find any declaration of `EIGEN_STL_UMAP`.
BTW, I've installed the latest version of colmap(commit [079b8ad](https://github.com/colmap/colmap/commit/079b8adb45524caab881b912dc1d28a69df5ae10)).
My env: Ubuntu 20.04, libeigen3-dev.

Can't figure out where does the problem come from. Looking forward for your help.

**Comment by ducha-aiki** [comment]
It is the recent colmap commit, which breaks the pycolmap...

**Comment by nnop** [comment]
Thanks. It's [this colmap PR](https://github.com/colmap/colmap/pull/1947) that *Remove unnecessary custom Eigen aligned allocator macros* breaks the pycolmap compilation. I'll switch to a previous commit.
