### ISSUE TITLE
pose_refinement: retrieve updated intrinsics

### ISSUE THREAD

**Issue by mokrueger** [colmap/pycolmap#150]
Hello there, 

I was trying to use the pycolmap.pose_refinement. Since there is an option to refine the intrinsic parameters (AbsolutePoseRefinementOptions.refine_focal_length and .refine_extra_params), I was wondering how to retrieve those.

I assumed they would be updated in place in the colmap::Camera object that is passed to the pose_refinement function. (as the function only returns the tvec and qvec of the refined extrinsics pose)
But it appears that this is not the case. Therefore I'm guessing this might be a bug, but feel free to correct me.

Kind regards

**Comment by sarlinpe** [comment]
Thank you for flagging this issue. This will be fixed in PR https://github.com/colmap/pycolmap/pull/175, the camera parameters will then be updated in-place.
