### ISSUE TITLE
Building is broken due to file/folder structure changes in Colmap

### ISSUE THREAD

**Issue by ChristopherRemde** [colmap/pycolmap#153]
**Issue:**
Due to very recent changes in the main colmap repo, where a lot of file / folder structures were moved, building is not possible, as the include paths don't match up anymore. During building you get errors like "colmap/base/xx.h No such file or directory"

See: https://github.com/colmap/colmap/commit/3c38248720e62efa8adeef94b156bddf48781a72 and https://github.com/colmap/colmap/commit/91068eac3f1ba0f871d0ea96e536dffaeda76630

**Solution:**
I created a PR to fix the paths: https://github.com/colmap/pycolmap/pull/152
Until the PR is accepted, you can alternativly use my fork, building should work there: https://github.com/ChristopherRemde/pycolmap, or alternativly, you need to build/install colmap with the commit at https://github.com/colmap/colmap/commit/7ea7fd23b1f84785537dffef07d30e662baea842 or earlier.

**Comment by sarlinpe** [comment]
This is now fixed, we're tracking COLMAP's HEAD again.
