### ISSUE TITLE
confused about image.camera_id

### ISSUE THREAD

**Issue by JerryDeepl** [colmap/pycolmap#154]
https://github.com/colmap/pycolmap/blob/743a4ac305183f96d2a4cfce7c7f6418b31b8598/reconstruction/image.cc#L94C17-L94C17

        .def_property(
            "camera_id", &Image::CameraId,
            [](Image& self, const camera_t camera_id) {
                THROW_CHECK_NE(camera_id, kInvalidCameraId);
                self.SetCameraId(**kInvalidCameraId**); // -> self.SetCameraId(**camera_id**);
            },

**Comment by sarlinpe** [comment]
Good catching, thanks - fixing it.
