### ISSUE TITLE
I encountered an error while building pycolmap from source code, manifested as: no matching function for call to 'ComputeAlignmentBetweenReconstructions (const colmap:: Reconstruction&, const colmap: Reconstruction&, const double&, const double&, Eigen:: Matrix3x4d *)'

### ISSUE THREAD

**Issue by XLionXL** [colmap/pycolmap#156]
[ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:17:
  /tmp/pip-req-build-jw_30qw7/transformations.cc: In lambda function:
  /tmp/pip-req-build-jw_30qw7/transformations.cc:85:49: error: no matching function for call to ‘ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, const double&, const double&, Eigen::Matrix3x4d*)’
     85 |                     max_reproj_error, &alignment);
        |                                                 ^
  In file included from /tmp/pip-req-build-jw_30qw7/estimators/generalized_absolute_pose.cc:9,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:10:
  /usr/local/include/colmap/geometry/similarity_transform.h:93:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, double, colmap::SimilarityTransform3*)’
     93 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:98:27: note:   no known conversion for argument 5 from ‘Eigen::Matrix3x4d*’ {aka ‘Eigen::Matrix<double, 3, 4>*’} to ‘colmap::SimilarityTransform3*’
     98 |     SimilarityTransform3* tgtFromSrc);
        |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, colmap::SimilarityTransform3*)’
    104 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note:   candidate expects 4 arguments, 5 provided
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:17:
  /tmp/pip-req-build-jw_30qw7/transformations.cc: In lambda function:
  /tmp/pip-req-build-jw_30qw7/transformations.cc:115:18: error: ‘const class colmap::SimilarityTransform3’ has no member named ‘TransformPoint’; did you mean ‘TransformPose’?
    115 |             self.TransformPoint(&cpy);
        |                  ^~~~~~~~~~~~~~
        |                  TransformPose
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc: In function ‘colmap::Reconstruction triangulate_points(colmap::Reconstruction, pybind11::object, pybind11::object, pybind11::object, bool, const colmap::IncrementalMapperOptions&)’:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:40:30: error: invalid initialization of reference of type ‘const std::shared_ptr<colmap::Reconstruction>&’ from expression of type ‘colmap::Reconstruction’
     40 |     RunPointTriangulatorImpl(reconstruction,
        |                              ^~~~~~~~~~~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/exe/sfm.h:40:44: note: in passing argument 1 of ‘int colmap::RunPointTriangulatorImpl(const std::shared_ptr<colmap::Reconstruction>&, const string&, const string&, const string&, const colmap::IncrementalMapperOptions&, bool)’
     40 |     const std::shared_ptr<Reconstruction>& reconstruction,
        |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc: In function ‘std::map<long unsigned int, colmap::Reconstruction> incremental_mapping(pybind11::object, pybind11::object, pybind11::object, const colmap::IncrementalMapperOptions&, pybind11::object)’:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:71:69: error: no matching function for call to ‘colmap::IncrementalMapperController::IncrementalMapperController(const colmap::IncrementalMapperOptions*, std::string&, std::string&, colmap::ReconstructionManager*)’
     71 |         &options, image_path, database_path, &reconstruction_manager);
        |                                                                     ^
  In file included from /usr/local/include/colmap/exe/sfm.h:35,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/controllers/incremental_mapper.h:163:3: note: candidate: ‘colmap::IncrementalMapperController::IncrementalMapperController(std::shared_ptr<const colmap::IncrementalMapperOptions>, const string&, const string&, std::shared_ptr<colmap::ReconstructionManager>)’
    163 |   IncrementalMapperController(
        |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/controllers/incremental_mapper.h:164:55: note:   no known conversion for argument 1 from ‘const colmap::IncrementalMapperOptions*’ to ‘std::shared_ptr<const colmap::IncrementalMapperOptions>’
    164 |       std::shared_ptr<const IncrementalMapperOptions> options,
        |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc: In lambda function:
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:88:32: error: ‘const class std::shared_ptr<colmap::Reconstruction>’ has no member named ‘Write’
     88 |                 reconstruction.Write(reconstruction_path);
        |                                ^~~~~
  /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:89:61: error: no match for ‘operator=’ (operand types are ‘std::map<long unsigned int, colmap::Reconstruction>::mapped_type’ {aka ‘colmap::Reconstruction’} and ‘const std::shared_ptr<colmap::Reconstruction>’)
     89 |                 reconstructions[prev_num_reconstructions] = reconstruction;
        |                                                             ^~~~~~~~~~~~~~
  In file included from /usr/local/include/colmap/exe/sfm.h:34,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/base/reconstruction.h:61:7: note: candidate: ‘colmap::Reconstruction& colmap::Reconstruction::operator=(const colmap::Reconstruction&)’
     61 | class Reconstruction {
        |       ^~~~~~~~~~~~~~
  /usr/local/include/colmap/base/reconstruction.h:61:7: note:   no known conversion for argument 1 from ‘const std::shared_ptr<colmap::Reconstruction>’ to ‘const colmap::Reconstruction&’
  /usr/local/include/colmap/base/reconstruction.h:61:7: note: candidate: ‘colmap::Reconstruction& colmap::Reconstruction::operator=(colmap::Reconstruction&&)’
  /usr/local/include/colmap/base/reconstruction.h:61:7: note:   no known conversion for argument 1 from ‘const std::shared_ptr<colmap::Reconstruction>’ to ‘colmap::Reconstruction&&’
  In file included from /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:26,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In function ‘bool ComputeRobustAlignmentBetweenPoints(const std::vector<Eigen::Matrix<double, 3, 1> >&, const std::vector<Eigen::Matrix<double, 3, 1> >&, double, double, Eigen::Matrix3x4d*)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:31:14: error: ‘SimilarityTransformEstimator’ was not declared in this scope
     31 |     LORANSAC<SimilarityTransformEstimator<3, kEstimateScale>,
        |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:31:60: error: template argument 1 is invalid
     31 |     LORANSAC<SimilarityTransformEstimator<3, kEstimateScale>,
        |                                                            ^
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:31:60: error: type/value mismatch at argument 2 in template parameter list for ‘template<class Estimator, class LocalEstimator, class SupportMeasurer, class Sampler> class colmap::LORANSAC’
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:31:60: note:   expected a type, got ‘kEstimateScale’
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:31:61: error: expected unqualified-id before ‘,’ token
     31 |     LORANSAC<SimilarityTransformEstimator<3, kEstimateScale>,
        |                                                             ^
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:32:42: error: expected initializer before ‘<’ token
     32 |              SimilarityTransformEstimator<3, kEstimateScale>>
        |                                          ^
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:35:25: error: ‘ransac’ was not declared in this scope
     35 |     const auto report = ransac.Estimate(src, dst);
        |                         ^~~~~~
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In function ‘colmap::SimilarityTransform3 AlignPosesBetweenReconstructions(colmap::Reconstruction&, const colmap::Reconstruction&, double, double)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:51:87: error: no matching function for call to ‘ComputeAlignmentBetweenReconstructions(colmap::Reconstruction&, const colmap::Reconstruction&, const double&, double&, Eigen::Matrix3x4d*)’
     51 |                                                           max_reproj_error, &alignment);
        |                                                                                       ^
  In file included from /tmp/pip-req-build-jw_30qw7/estimators/generalized_absolute_pose.cc:9,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:10:
  /usr/local/include/colmap/geometry/similarity_transform.h:93:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, double, colmap::SimilarityTransform3*)’
     93 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:98:27: note:   no known conversion for argument 5 from ‘Eigen::Matrix3x4d*’ {aka ‘Eigen::Matrix<double, 3, 4>*’} to ‘colmap::SimilarityTransform3*’
     98 |     SimilarityTransform3* tgtFromSrc);
        |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, colmap::SimilarityTransform3*)’
    104 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note:   candidate expects 4 arguments, 5 provided
  In file included from /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:26,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:54:20: error: cannot convert ‘colmap::SimilarityTransform3’ to ‘const colmap::Sim3d&’
     54 |     self.Transform(tform);
        |                    ^~~~~
        |                    |
        |                    colmap::SimilarityTransform3
  In file included from /usr/local/include/colmap/exe/sfm.h:34,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/base/reconstruction.h:190:31: note:   initializing argument 1 of ‘void colmap::Reconstruction::Transform(const colmap::Sim3d&)’
    190 |   void Transform(const Sim3d& tform);
        |                  ~~~~~~~~~~~~~^~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:26,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In function ‘colmap::SimilarityTransform3 AlignPointsBetweenReconstructions(colmap::Reconstruction&, const colmap::Reconstruction&, int, double, double)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:105:20: error: cannot convert ‘colmap::SimilarityTransform3’ to ‘const colmap::Sim3d&’
    105 |     self.Transform(tform);
        |                    ^~~~~
        |                    |
        |                    colmap::SimilarityTransform3
  In file included from /usr/local/include/colmap/exe/sfm.h:34,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/base/reconstruction.h:190:31: note:   initializing argument 1 of ‘void colmap::Reconstruction::Transform(const colmap::Sim3d&)’
    190 |   void Transform(const Sim3d& tform);
        |                  ~~~~~~~~~~~~~^~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:26,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In function ‘colmap::SimilarityTransform3 AlignReconstruction(colmap::Reconstruction&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<Eigen::Matrix<double, 3, 1> >&, int)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:116:25: error: ‘class colmap::Reconstruction’ has no member named ‘Align’
    116 |     bool success = self.Align(image_names, locations, min_common_images, &tform);
        |                         ^~~~~
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In function ‘colmap::SimilarityTransform3 RobustAlignReconstruction(colmap::Reconstruction&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<Eigen::Matrix<double, 3, 1> >&, int, double, double)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:132:25: error: ‘class colmap::Reconstruction’ has no member named ‘AlignRobust’
    132 |     bool success = self.AlignRobust(image_names, locations, min_common_images, options, &tform);
        |                         ^~~~~~~~~~~
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc: In lambda function:
  /tmp/pip-req-build-jw_30qw7/reconstruction/utils.cc:198:67: error: no matching function for call to ‘ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, const double&, const double&, Eigen::Matrix3x4d*)’
    198 |                                                         &alignment)) {
        |                                                                   ^
  In file included from /tmp/pip-req-build-jw_30qw7/estimators/generalized_absolute_pose.cc:9,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:10:
  /usr/local/include/colmap/geometry/similarity_transform.h:93:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, double, colmap::SimilarityTransform3*)’
     93 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:98:27: note:   no known conversion for argument 5 from ‘Eigen::Matrix3x4d*’ {aka ‘Eigen::Matrix<double, 3, 4>*’} to ‘colmap::SimilarityTransform3*’
     98 |     SimilarityTransform3* tgtFromSrc);
        |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note: candidate: ‘bool colmap::ComputeAlignmentBetweenReconstructions(const colmap::Reconstruction&, const colmap::Reconstruction&, double, colmap::SimilarityTransform3*)’
    104 | bool ComputeAlignmentBetweenReconstructions(
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/geometry/similarity_transform.h:104:6: note:   candidate expects 4 arguments, 5 provided
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc: In lambda function:
  /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:211:32: error: cannot convert ‘colmap::SimilarityTransform3’ to ‘const colmap::Sim3d&’
    211 |                 self.Transform(tform);
        |                                ^~~~~
        |                                |
        |                                colmap::SimilarityTransform3
  In file included from /usr/local/include/colmap/exe/sfm.h:34,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/base/reconstruction.h:190:31: note:   initializing argument 1 of ‘void colmap::Reconstruction::Transform(const colmap::Sim3d&)’
    190 |   void Transform(const Sim3d& tform);
        |                  ~~~~~~~~~~~~~^~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:26:
  /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc: In function ‘void init_reconstruction(pybind11::module&)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/reconstruction.cc:216:40: error: ‘Merge’ is not a member of ‘colmap::Reconstruction’
    216 |         .def("merge", &Reconstruction::Merge,
        |                                        ^~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/main.cc:27:
  /tmp/pip-req-build-jw_30qw7/reconstruction/correspondence_graph.cc: In function ‘void init_correspondence_graph(pybind11::module&)’:
  /tmp/pip-req-build-jw_30qw7/reconstruction/correspondence_graph.cc:60:71: error: ‘FindTransitiveCorrespondences’ is not a member of ‘colmap::CorrespondenceGraph’
     60 |         .def("find_transitive_correspondences", &CorrespondenceGraph::FindTransitiveCorrespondences)
        |                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /tmp/pip-req-build-jw_30qw7/pybind11/include/pybind11/pybind11.h:17,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:1:
  /tmp/pip-req-build-jw_30qw7/pybind11/include/pybind11/detail/init.h: In instantiation of ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = colmap::IncrementalTriangulator; Args = {colmap::CorrespondenceGraph*, colmap::Reconstruction*}; typename std::enable_if<(! std::is_constructible<_Tp, _Args>::value), int>::type <anonymous> = 0]’:
  /tmp/pip-req-build-jw_30qw7/pybind11/include/pybind11/detail/init.h:178:66:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<colmap::IncrementalTriangulator, std::shared_ptr<colmap::IncrementalTriangulator> >; Extra = {}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {colmap::CorrespondenceGraph*, colmap::Reconstruction*}]’
  /tmp/pip-req-build-jw_30qw7/pybind11/include/pybind11/pybind11.h:1408:9:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {colmap::CorrespondenceGraph*, colmap::Reconstruction*}; Extra = {}; type_ = colmap::IncrementalTriangulator; options = {std::shared_ptr<colmap::IncrementalTriangulator>}]’
  /tmp/pip-req-build-jw_30qw7/reconstruction/incremental_triangulator.cc:39:63:   required from here
  /tmp/pip-req-build-jw_30qw7/pybind11/include/pybind11/detail/init.h:63:64: error: no matching function for call to ‘colmap::IncrementalTriangulator::IncrementalTriangulator(<brace-enclosed initializer list>)’
     63 | inline Class *construct_or_initialize(Args &&...args) { return new Class{std::forward<Args>(args)...}; }
        |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/local/include/colmap/sfm/incremental_mapper.h:38,
                   from /usr/local/include/colmap/controllers/incremental_mapper.h:35,
                   from /usr/local/include/colmap/exe/sfm.h:35,
                   from /tmp/pip-req-build-jw_30qw7/pipeline/sfm.cc:3,
                   from /tmp/pip-req-build-jw_30qw7/main.cc:22:
  /usr/local/include/colmap/sfm/incremental_triangulator.h:92:3: note: candidate: ‘colmap::IncrementalTriangulator::IncrementalTriangulator(std::shared_ptr<const colmap::CorrespondenceGraph>, std::shared_ptr<colmap::Reconstruction>)’
     92 |   IncrementalTriangulator(
        |   ^~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/sfm/incremental_triangulator.h:93:50: note:   no known conversion for argument 1 from ‘colmap::CorrespondenceGraph*’ to ‘std::shared_ptr<const colmap::CorrespondenceGraph>’
     93 |       std::shared_ptr<const CorrespondenceGraph> correspondence_graph,
        |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/sfm/incremental_triangulator.h:43:7: note: candidate: ‘colmap::IncrementalTriangulator::IncrementalTriangulator(const colmap::IncrementalTriangulator&)’
     43 | class IncrementalTriangulator {
        |       ^~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/colmap/sfm/incremental_triangulator.h:43:7: note:   candidate expects 1 argument, 2 provided
  /usr/local/include/colmap/sfm/incremental_triangulator.h:43:7: note: candidate: ‘colmap::IncrementalTriangulator::IncrementalTriangulator(colmap::IncrementalTriangulator&&)’
  /usr/local/include/colmap/sfm/incremental_triangulator.h:43:7: note:   candidate expects 1 argument, 2 provided
  make[2]: *** [CMakeFiles/pycolmap.dir/build.make:63: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/pycolmap.dir/all] Error 2
  make: *** [Makefile:84: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-jw_30qw7/setup.py", line 83, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-jw_30qw7/setup.py", line 35, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-jw_30qw7/setup.py", line 78, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
  ----------------------------------------

**Comment by XLionXL** [comment]
PS：this is my colmap version：
COLMAP 3.9 -- Structure-from-Motion and Multi-View Stereo
              (Commit 649d58c4 on 2023-07-14 with CUDA)
Pycolmap is also the latest version

**Comment by Skydes** [comment]
Use tags 3.8 for COLMAP and v.0.4.0 for pycolmap, master branches are currently unstable.

**Comment by XLionXL** [comment]
> 使用 COLMAP 的标签 3.8 和 pycolmap 的 v.0.4.0，主要分支目前不稳定。

Thank you for your prompt reply. I will now try the combination of version 3.8 colmap and version 0.4.0 pycolmap to see if it works properly

**Comment by XLionXL** [comment]
> Use tags 3.8 for COLMAP and v.0.4.0 for pycolmap, the main branches are currently unstable.

Through your suggestion, I have successfully installed them. Thank you very much!
