### ISSUE TITLE
Reduce the size of macOS wheels

### ISSUE THREAD

**Issue by sarlinpe** [colmap/pycolmap#161]
Use Boost built from source with ICU disabled:
https://github.com/colmap/pycolmap/blob/6bfe48468d0e73005f4a4e2d97787761a8a1a68b/package/build-wheels-macos.sh#L76-L84

Fails with linking issue: https://github.com/colmap/pycolmap/actions/runs/6042365188/job/16397322142

**Comment by abhiagg92** [comment]
Could you please tell me the installed CMake version in macOS runner?

**Comment by sarlinpe** [comment]
We pull the latest version:
https://github.com/colmap/pycolmap/blob/05abbd037bc303f746a096a52783851bff990dd5/package/build-wheels-macos.sh#L22
[From latest logs](https://github.com/colmap/pycolmap/actions/runs/6328054645/job/17185323212) (not sure you're able to see it), it's 3.27.6

**Comment by sarlinpe** [comment]
Solved with https://github.com/colmap/pycolmap/commit/3f2b219508dcc87ba175456a20d230e6508dd1d9.
