### ISSUE TITLE
PyColmap build failure

### ISSUE THREAD

**Issue by abhiagg92** [colmap/pycolmap#180]
I am trying to build Pycolmap from scratch using the latest master branch (`940eff6`) and the recommended colmap version i.e. `0d9ab40`. But running `pip install .` returns the following exception

```
CMake Error at CMakeLists.txt:20 (target_link_libraries):
      Target "pycolmap" links to:
    
        colmap::colmap
    
      but the target was not found.  Possible reasons include:
    
        * There is a typo in the target name.
        * A find_package call is missing for an IMPORTED target.
        * An ALIAS target is missing.
```

I have verified that the colmap is running fine and there is no issue with colmap installation. I am able to fix this issue by replacing 

```
find_package(COLMAP REQUIRED)
```
with 
```
find_package(colmap REQUIRED)
```
in CMakeLists.txt file. I can create a PR to fix this issue.

**Comment by sarlinpe** [comment]
You need to use PyCOLMAP's tag v0.4.0
```bash
git checkout v0.4.0
```
I've now updated the README to clarify this.
