### ISSUE TITLE
How to visualize camera poses

### ISSUE THREAD

**Issue by khayamgondal** [colmap/pycolmap#193]
I have a transforms.json file that contains camera extrinsic and intrinsic. How can I visualize them?

**Comment by mihaidusmanu** [comment]
There is no support for JSON transforms in either COLMAP or PyCOLMAP. If you plan to use COLMAP / PyCOLMAP, you will need to convert this file to the COLMAP equivalent https://colmap.github.io/format.html#text-format

Closed as offtopic.
