### ISSUE TITLE
Which images do 3D points belong to?

### ISSUE THREAD

**Issue by YuyanHuang** [colmap/pycolmap#194]
Hi,

After calculating the sparse point cloud through sfm (pycolmap.incremental_mapping), how to determine which images each point in the point cloud belongs to?

Thanks.

**Comment by sarlinpe** [comment]
```python
p3D_ids = list(reconstruction.points3D)
i = point3D_ids[0]
p3D = reconstruction.points3D[i]
image_ids = [el.image_id for el in p3D.track.elements]
```
