### ISSUE TITLE
About the module of pycolmap

### ISSUE THREAD

**Issue by ywaison** [colmap/pycolmap#195]
How to solve the problem about "AttributeError: module 'pycolmap' has no attribute 'SceneManager'"

**Comment by tourbliu** [comment]
hi，have you resolved？

**Comment by sarlinpe** [comment]
There is no such thing as a `SceneManager` in either COLMAP or PyCOLMAP.

**Comment by nlml** [comment]
I think you're looking for this pycolmap ;) 
https://github.com/trueprice/pycolmap

**Comment by j71200** [comment]
Thanks to nlml. I just encountered this issue. What I need is exactly [https://github.com/trueprice/pycolmap](url)
You can install it throught:
`pip install git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e`
