### ISSUE TITLE
Fail to import pycolmap

### ISSUE THREAD

**Issue by zym-njust** [colmap/pycolmap#196]
I have successfully downloaded colmap 3.8 and build pycolmap from rescource. But when import pycolmap, I meet this error

`(ldm) ym@ym-ubuntu:~/project/sfm$ python
Python 3.8.5 (Fri Jan 13 20:30:28 CST 2023)
[Graal, GraalVM CE, Java 17.0.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot load /home/ym/anaconda3/envs/ldm/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib/python3.8/site-packages/pycolmap.graalpy223-38-native-x86_64-linux.so: /home/ym/anaconda3/envs/ldm/lib/python3.8/site-packages/pycolmap.graalpy223-38-native-x86_64-linux.so: undefined symbol: PyExc_ValueError`

The result after building wheels for pycolmap is shown as below

`Processing /home/ym/app/pycolmap
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... done
  Created wheel for pycolmap: filename=pycolmap-0.4.0-graalpy38-graalpy223_38_native-linux_x86_64.whl size=16789870 sha256=205397541233c33add760b164ca7173f710c57a5e7fe9e6913e297f1f7951796
  Stored in directory: /tmp/pip-ephem-wheel-cache-ywrd0b_4/wheels/26/e5/81/099ec89dc143c3b58b67af158b72c3642863344e101985143f
Successfully built pycolmap

- INFO: Choosing GraalPy tested version 7 for pytest>=6; extra == "testing"
- INFO: Choosing GraalPy tested version 1.16.4 for numpy
- INFO: Choosing GraalPy tested version 1.3.1 for scipy
- INFO: Choosing GraalPy tested version 3.3.2 for matplotlib; extra == "all"
- INFO: Choosing GraalPy tested version 0.25.0 for pandas>=0.20.3
- INFO: Choosing GraalPy tested version 20.1.1 for pip>=19.1
- INFO: Choosing GraalPy tested version 0.5.1 for asv; extra == "test"
- INFO: Choosing GraalPy tested version 3.4.7 for cryptography>=3.0.0; extra == "rsa"

Installing collected packages: pycolmap
Successfully installed pycolmap-0.4.0`

Is there version conflict about GraalPy?

**Comment by mihaidusmanu** [comment]
Seems like your pycolmap build is being linked against the wrong libpython. You probably have an os-wide python / libpython installation that conflicts with the graalpyone.

**Comment by sarlinpe** [comment]
I am not even sure that pybind is compatible with GraalPy.
