### ISSUE TITLE
issue with git clone PYCOLMAP sources

### ISSUE THREAD

**Issue by antoinebio** [colmap/pycolmap#197]
git clone -b v0.4.0 --recursive git@github.com:colmap/pycolmap.git

returns that error
<img width="506" alt="image" src="https://github.com/colmap/pycolmap/assets/30265851/9e567ce6-29b3-48aa-b56d-d7de1956a07f">

**Comment by sarlinpe** [comment]
How about this?
```bash
git clone -b v0.4.0 --recursive https://github.com/colmap/pycolmap.git
```

**Comment by antoinebio** [comment]
Hello @sarlinpe ,
I understand that pycolmap can only be installed on linux OS.... Do you confirm ?

or is it compatible with windows os ?

I would like to test colmap on very large ground based datasets with arguments such like 

hloc
pixsfm

and compare SFM performance vs commercial SFM such as metashape.
