### ISSUE TITLE
Attribute focal_length_x causes crash

### ISSUE THREAD

**Issue by BlGene** [colmap/pycolmap#199]
Hi,
I just noticed that calling `focal_length_x` attribute causes python to crash. I guess this is not intended.

```
from pathlib import Path
from pycolmap import Reconstruction
sfm_path = Path("/tmp/xyz") / "outputs" / "sfm"
rec = Reconstruction(str(sfm_path))
for image_id, image in rec.images.items():
    camera = rec.cameras[image.camera_id]
    break
camera = rec.cameras[image.camera_id]
print(camera.focal_length_x)
print("done.")
```

This gives the error message:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1123 16:49:56.770359 223369 camera.cc:117] Check failed: idxs.size() == 2 (1 vs. 2) 
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by mihaidusmanu** [comment]
Maybe your reconstruction has simple pinhole cameras with the same focal
length for x and y? In that case you can get it directly with
`.focal_length`

**Comment by BlGene** [comment]
Hi @mihaidusmanu,
Thanks for the quick reply. Yes, this worked for me. Should I leave the issue open, because the crash is not desired, or should I close it?

**Comment by sarlinpe** [comment]
This has been fixed upstream in https://github.com/colmap/colmap/pull/2301 - thanks!
