### ISSUE TITLE
Data corruption when loading several reconstructions (Reconstruction object is destroyed by garbage collector, while accessing it's children objects))

### ISSUE THREAD

**Issue by qchenevier** [colmap/pycolmap#212]
Hello everyone,

When loading several reconstructions in memory using pycolmap, I noticed that only the last loaded reconstruction has valid data. It seems that loading a reconstruction overwrites in memory the reconstructions which have been loaded before.

I noticed that when comparing several reconstructions by plotting the track length vs the error for all the points 3D.

Here is an example in pseudo-code:

There is **no corruption** if I load the reconstruction and **extract the data before loading the next** one:
```python
dataframes = []
for reconstruction_directory in reconstruction_directories:
    reconstruction = pycolmap.Reconstruction(reconstruction_directory)
    dataframes.append(extract_data(reconstruction))
plot_track_length_vs_error(dataframes)
```
Here is the plot I get (data seems normal):
<img width="755" alt="image" src="https://github.com/colmap/pycolmap/assets/24975491/5e055905-5058-4ae6-9153-6f15a63e4b2a">

But **data is corrupted** if I **load everything then extract everything**

[Edit: Actually, it's more complicated than that, the pseudo-code below should be working. The issue arise when we use objects extracted from the reconstruction, after it has been destroyed by the garbage collector. See comment after.]:
```python
reconstructions = []
dataframes = []

for reconstruction_directory in reconstruction_directories:
    reconstruction = pycolmap.Reconstruction(reconstruction_directory)
    reconstructions.append(reconstruction)

for reconstruction in reconstructions:
    dataframes.append(extract_data(reconstruction))
```

Here is the plot I get (data is corrupted: please notice the log scale):
<img width="753" alt="image" src="https://github.com/colmap/pycolmap/assets/24975491/d6ee7cc6-658a-417d-8d84-d988298b3960">

**Comment by sarlinpe** [comment]
Thanks for reporting this. I'll look into this when I find some time, but for now could you please share the following details:
1. System information: OS, python version, commit hash for COLMAP & PyCOLMAP
2. Could narrow down which data gets corrupted? do attributes like image name, pose, camera parameters, etc. get corrupted too? or does this affect only the points?
3. Could try this again by building at HEAD for both COLMAP and PyCOLMAP?
4. Would you manage to reproduce & check for this with a minimal example? ideally with synthetic data?

**Comment by qchenevier** [comment]
Sure, I'll do that. Let me a few hours (maybe Monday).

**Comment by qchenevier** [comment]
Ho I think I get it. This is an issue with the garbage collector. It releases the memory used by the reconstruction, whereas some python objects (points3D) extracted from it are still pointing to the data.

Here is a minimal example:
```python
import numpy as np

reconstruction = pycolmap.Reconstruction()
for i in range(1):
    reconstruction.add_point3D(
        xyz=np.array([0, 0, 0], dtype=np.float64),
        color=np.array([0, 0, 0], dtype=np.uint8),
        track=pycolmap.Track(),
    )
point3D_from_first_reconstruction = list(reconstruction.points3D.values())[0]
print(point3D_from_first_reconstruction.summary())

reconstruction = pycolmap.Reconstruction()
for i in range(100):
    reconstruction.add_point3D(
        xyz=np.array([1, 1, 1], dtype=np.float64),
        color=np.array([1, 1, 1], dtype=np.uint8),
        track=pycolmap.Track(),
    )

print("Print again the point3D from the first reconstruction (this should stay the same):")
print(point3D_from_first_reconstruction.summary())
```

Here's the output:

Sometimes the data is overwritten:
```
Point3D:
	xyz = [0 0 0]
	track_length = 0
	error = -1
	color = [0 0 0]
Print again the point3D from the first reconstruction (this should stay the same):
Point3D:
	xyz = [1 1 1]
	track_length = 0
	error = -1
	color = [1 1 1]
```

Sometimes the data is just corrupted:
```
Point3D:
	xyz = [0 0 0]
	track_length = 0
	error = -1
	color = [0 0 0]
Print again the point3D from the first reconstruction (this should stay the same):
Point3D:
	xyz = [           0            0 5.02035e+175]
	track_length = 423303209040206496
	error = 4.01333e-57
	color = [34 58 32]
```


One way to avoid that is to avoid loosing the reference to the first object:
```python
reconstruction = pycolmap.Reconstruction()
# do stuff

reconstruction_2 = pycolmap.Reconstruction()
# do stuff
```

In my for loop, loading several reconstructions, I solved it by adding a list storing all the recontruction objects:

```python
reconstructions = []
for directory in directories
    reconstruction = pycolmap.Reconstruction(directory)
    # do stuff
    reconstructions.append(reconstruction)  # objects extracted from reconstructions are not corrupted if we keep them in memory
```

**Comment by qchenevier** [comment]
To be fair, that's a corner case. I think a description of this behavior in the README would be enough.

**Comment by sarlinpe** [comment]
It's in fact a pretty serious issues, it should be fixed by https://github.com/colmap/pycolmap/pull/213

**Comment by qchenevier** [comment]
Hmmm... I'm on macos and I'm not familiar with the pycolmap/colmap install process from the git repo. Usually I use mamba/conda or pip with already-built wheels.

I tried to install pycolmap from source, in 2 configurations:
- colmap from conda-forge --> colmap install OK, but missing files for compilation then when installing pycolmap.
- colmap from source using `./package/install-colmap-macos.sh` --> colmap install FAILED, not able to write to `/usr/local/share`. Do you usually need to sudo this installation or is it related to my local setup ?

**Comment by qchenevier** [comment]
The PR's CI says that there are builds for macos but I couldn't find a link: 
<img width="831" alt="image" src="https://github.com/colmap/pycolmap/assets/24975491/541e79e9-aae0-408c-84f2-0c46cc743910">

**Comment by sarlinpe** [comment]
Are you able to download the wheels from https://github.com/colmap/pycolmap/actions/runs/7245895609?pr=213 ?

**Comment by sarlinpe** [comment]
Great! GitHub doesn't yet provide free macOS arm64 instances so we cannot build these wheels for now.
