### ISSUE TITLE
Is the model_aligner feature from COLMAP exposed in pycolmap?

### ISSUE THREAD

**Issue by LauroLdas** [colmap/pycolmap#215]
Hey guys,

This is more a question than a properly issue, but here it goes:

I'm interested in using the model_aligner (https://colmap.github.io/faq.html) feature from COLMAP, but I'm just found a way to use it using the command line interface from COLMAP. Is this exposed in the library? Can we get it exposed in the Python binds for pycolmap?

Thank you.

**Comment by sarlinpe** [comment]
We don't yet have bindings for the `model_aligner` but we will in the future. For now you can use `pycolmap.align_reconstrution_to_locations` on HEAD (or `pycolmap.Reconstruction.align_robust` in v0.4.0) to emulate the `alignment_type = ecef | enu` behavior by first converting the GPS locations to ECEF/ENU.

**Comment by LauroLdas** [comment]
Thanks for your prompt response.
Is there any docs I can look for the input parameters of the `pycolmap.align_reconstrution_to_locations` function?

**Comment by sarlinpe** [comment]
Check the code:
https://github.com/colmap/pycolmap/blob/bb1732139c800ddf5336bdfc9e5e24053351d47d/pycolmap/estimators/alignment.h#L100-L105

**Comment by LauroLdas** [comment]
Hmm... I'm using v.0.4.0 and trying to find the align_robust code, but I can't find it. Just used the search on github. In which file can I find the definition?

**Comment by LauroLdas** [comment]
hey @sarlinpe thank you for your precious help. I got it working perfectly with align_robust.

**Comment by messileonardo** [comment]
Hi there, @LauroLdas please could you provide an example on how did you use "align_robust" or "align_reconstrution_to_locations"? An example of how did you set the line of code would help me a lot!
Many thanks in advance!
