### ISSUE TITLE
master branch doesn't have setup.py file

### ISSUE THREAD

**Issue by shubham-monarch** [colmap/pycolmap#226]
I need to work with the commit [#89ce83](https://github.com/colmap/pycolmap/tree/89ce832326e91a63a1188bdeacc2888f15477cea). To make it work, I have checked out to the appropriate `COLMAP` version, and built + installed it. 

However, I am facing issue installing `pycolmap` for the aforementioned commit. I have been using `pip install .` but that doesn't seem to be working. More specifically, I am getting the error — 

`The link interface of target "colmap::colmap_scene" contains: 
      SQLite::SQLite3 
    but the target was not found.  Possible reasons include: 
      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing. `
     
The repo also doesn't seem to contain any `setup.py` file corresponding to the commit. What am I missing?

Also, probably a very navie question —  since `setup.py` is missing, how come `pip install .` is working in the first place?

**Comment by sarlinpe** [comment]
- We need to update the doc: the commit that you reference requires COLMAP 3.9. Does the error still occur at that point?
- We recently switched from `setup.py` to `pyproject.toml`, which is now the recommended way of managing builds. I think that this requires `pip>=10.0`.

**Comment by shubham-monarch** [comment]
I checked out to `COLMAP 3.9` and built and installed it.  On running `pip install .` , I am still getting the same error  —

```
CMake Error at /usr/local/share/colmap/colmap-targets.cmake:138 (set_target_properties):
    The link interface of target colmap::colmap_scene contains:
      SQLite::SQLite3
    but the target was not found.  Possible reasons include:
      - There is a typo in the target name.
      - A find_package call is missing for an IMPORTED target.
      - An ALIAS target is missing.
 Call Stack (most recent call first):
    /usr/local/share/colmap/colmap-config.cmake:105 (include)
    CMakeLists.txt:21 (find_package)
```
```
  CMake Error at /usr/local/share/colmap/colmap-targets.cmake:159 (set_target_properties):
    The link interface of target "colmap::colmap_util" contains:
      SQLite::SQLite3
    but the target was not found.  Possible reasons include:
      - There is a typo in the target name.
      - A find_package call is missing for an IMPORTED target.
      - An ALIAS target is missing.
  Call Stack (most recent call first):
    /usr/local/share/colmap/colmap-config.cmake:105 (include)
    CMakeLists.txt:21 (find_package)
   Generating done (0.0s)
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  CMake configuration failed
  ERROR: Failed building wheel for pycolmap
```

**Comment by sarlinpe** [comment]
Can you include the full log? Can you try to swap the 2 include lines in `/usr/local/share/colmap/colmap-config.cmake`: https://github.com/colmap/colmap/blob/71cebde85b5ce290c93f67326eea7c1b1c0cea97/cmake/colmap-config.cmake.in#L81-L82

**Comment by shubham-monarch** [comment]
Already tried swapping those 2 lines. Doesn't help. 
I am attaching the complete log for your reference.
[log.txt](https://github.com/colmap/pycolmap/files/13886526/log.txt)

**Comment by sarlinpe** [comment]
Thanks!
```
-- Found SQLite3
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libsqlite3.so
```
Corresponds to the old, broken [`FindSQLite3.cmake`](https://github.com/colmap/colmap/blob/3.8/cmake/FindSQLite3.cmake) shipped in COLMAP <= 3.8; CMake>=3.14 ships it own `FindSQLite3.cmake`, which defines the `SQLite::SQLite3` target: https://cmake.org/cmake/help/latest/module/FindSQLite3.html Maybe you didn't properly uninstall 3.8 and the file `/usr/local/share/colmap/cmake/FindSQLite3.cmake` remains?

**Comment by shubham-monarch** [comment]
@sarlinpe what would be the best way to uninstall `colmap 3.8`?

**Comment by sarlinpe** [comment]
This should work:
```
rm -rf /usr/local/bin/colmap /usr/local/share/colmap/ /usr/local/include/colmap/ /usr/local/lib/libcolmap*  /usr/local/share/applications/COLMAP.desktop
```
