### ISSUE TITLE
`'pycolmap.Image' object has no attribute 'rotmat'`

### ISSUE THREAD

**Issue by vitalii-p** [colmap/pycolmap#246]
In hloc I got an error during visualization ([viz_3d.plot_reconstruction](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz_3d.py#L152))

`'pycolmap.Image' object has no attribute 'rotmat'`

Could you suggest how to fix this issue? How can I get rotation matrix or quaternion from Image object?

**Comment by vitalii-p** [comment]
Seems like here it is 

`image.cam_from_world.rotation.matrix().real`

**Comment by sarlinpe** [comment]
This is being is fixed in https://github.com/cvg/Hierarchical-Localization/pull/353 following recent updates to pycolmap.

**Comment by sarlinpe** [comment]
https://github.com/cvg/Hierarchical-Localization/pull/353 has been merged.
