### ISSUE TITLE
AttributeError: module 'pycolmap' has no attribute 'Database'

### ISSUE THREAD

**Issue by fdengmark** [colmap/pycolmap#247]
All I have done is pip install pycolmap on an Ubuntu machine. I'm trying to run the example.py script and it looks like I didn't install pycolmap appropriately.

**Comment by sarlinpe** [comment]
The database bindings were added after v0.5.0 was released on PyPI, we'll push a new release soon. In the meantime you'll have to build from source.

**Comment by sarlinpe** [comment]
We have pushed a new release: https://github.com/colmap/pycolmap/releases/tag/v0.6.0
