### ISSUE TITLE
Trying to install pycolmap either via the pip or via source not working 

### ISSUE THREAD

**Issue by dhruvmalik007** [colmap/pycolmap#249]
## Problem: 

I have installed via `pip install pycolmap` but there is no installation of the package and I am not able to import the package, at the same time if I am trying to install via source build `git clone -b master GitHub.com/colmap/pycolmap && cd pycolmap && python -m  pip install .` there is build error.

**Comment by sarlinpe** [comment]
Please clearly report the error encountered with fulls logs, the expected behavior, and the specifications of your system (OS, Python version, etc.)

**Comment by dhruvmalik007** [comment]
sure: 

Logs for the pycolmap installation: 

- via `pip install pycolmap` in the virtualenv in visual studio code : 
<img width="387" alt="image" src="https://github.com/colmap/pycolmap/assets/29146213/ad8bd284-6dfe-4f5a-b03f-a2a31ead2f70">


even when I set correctly the python interpreter.

- but doing same in the ipython and colab the package works successfully.


 I am using AWS EC2 instance with the following value of `uname -a` = 5.15.0-1045-aws.

**Comment by sarlinpe** [comment]
These are not logs.
