### ISSUE TITLE
May I ask about the changes in the new version？

### ISSUE THREAD

**Issue by Zeng-Fan-Yi** [colmap/pycolmap#260]
When I use a new version of pycolmap, I often see `pycolmap' Image 'object has no attribute' rotmat `or ` pycolmap ' Image 'object has no attribute' tvec `error. I know that CamFromWorld replace qvec/tvec in the new version. So what should I do if I want to use code similar to ` img. rotmat() ` or `img. tvec` in the new version?

**Comment by sarlinpe** [comment]
hloc has been updated to support the new version: https://github.com/cvg/Hierarchical-Localization/commit/936040e8d67244cc6c8c9d1667701f3ce87bf075#diff-0de4cbc99c18b9dc5d1222addb08b24427cced6514d6a54ffae72bb2c860d701R153-R154
