### ISSUE TITLE
pycolmap build from source error 

### ISSUE THREAD

**Issue by ahndroo** [colmap/pycolmap#268]
Building pycolmap in a Docker container where the main branch of colmap is installed.  

Host machine: Ubuntu 22.04, CUDA 12.4
Docker image: Ubuntu 22.04, CUDA 11.7 (had issues building colmap with 12), ceres 2.2 (from source), colmap (main branch)

The error is summarized here:

`
        Could not find a configuration file for package "colmap" that is compatible  with requested version "3.9.1".  
        The following configuration files were considered but not accepted:  
          /usr/local/share/colmap/colmap-config.cmake, version: 3.10-dev
`

It seems the pycolmap isn't compatible with the main colmap branch yet.  I had several issues building with colmap 3.9.1 but was successful with the main branch.  Is there any versions of pycolmap that support this version?

Full log output from `python3 -m pip install .` attached
[log.txt](https://github.com/colmap/pycolmap/files/14641494/log.txt)

**Comment by sarlinpe** [comment]
As the mentioned in the README, if you want to build from COLMAP HEAD, please use the new fork that lives in the COLMAP repository: https://github.com/colmap/colmap/tree/main/pycolmap
