### ISSUE TITLE
Building package is failed

### ISSUE THREAD

**Issue by yuliagrinclk** [colmap/pycolmap#27]
I am trying to install pycolmap. But I cannot install openblas package with vcpkg.
here are my parameters:
Python 3.6
Microsoft Visual Studio 2019
Windows 10

And here the Error I get:
Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openblas]+Build+error
including:
  package: openblas[core]:x64-windows -> 0.3.15#1
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 3a68454af 2021-11-27 (31 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by ZZWang21** [comment]
Can I ask Why install  openblas?

**Comment by sarlinpe** [comment]
Check `package/install-colmap-windows.ps1` for an example of how to build dependencies on Windows.
