### ISSUE TITLE
absolute_pose_estimation

### ISSUE THREAD

**Issue by Bin-ze** [colmap/pycolmap#270]
I try to use absolute_pose_estimation to calculate the camera pose of the newly added scene.
I want to know whether BA is used to optimize the camera pose after calling absolute_pose_estimation, or whether it follows the PnP settings and calculates the analytical solution of the camera pose.

**Comment by sarlinpe** [comment]
Yes, the pose is refined with least-squares optimization following PnP+RANSAC.
https://github.com/colmap/colmap/blob/0ea2d5ceee1360bba427b2ef61f1351e59a46f91/src/pycolmap/estimators/absolute_pose.cc#L42-L51
