### ISSUE TITLE
Bind Iterative Global SfM 

### ISSUE THREAD

**Issue by jytime** [colmap/pycolmap#273]
Hi,

I was wondering is it possible to bind the [IterativeGlobalRefinement](https://github.com/colmap/colmap/blob/187a4e1a6afead76a8aba76f0a48f9fcb9117bb7/src/colmap/sfm/incremental_mapper.cc#L771) function or something similar? We are currently using the [bundle adjustment](https://github.com/colmap/pycolmap/blob/b6627db2266f098c21c3d7e4b7844b4b90d8e02d/pycolmap/pipeline/sfm.h#L358) of pycolmap for the [iterative_global_BA](https://github.com/facebookresearch/vggsfm/blob/dd513a45595f5b0bdb2be5ae074ec4b210eee9df/vggsfm/utils/triangulation.py#L561
) function in our repository. The function is called [here](https://github.com/facebookresearch/vggsfm/blob/dd513a45595f5b0bdb2be5ae074ec4b210eee9df/vggsfm/models/triangulator.py#L206). 

It works well and the performance is reasonable. However, since pycolmap.bundle_adjustment currently does not cover the operations like [Retriangulate](https://github.com/colmap/colmap/blob/187a4e1a6afead76a8aba76f0a48f9fcb9117bb7/src/colmap/sfm/incremental_mapper.cc#L779) or [FilterPoints](https://github.com/colmap/colmap/blob/187a4e1a6afead76a8aba76f0a48f9fcb9117bb7/src/colmap/sfm/incremental_mapper.cc#L789C33-L789C45), we are compelled to convert the data between PyTorch tensors and pycolmap objects for each iteration. We suspect this might not be the most efficient approach.

I have observed that this appears to be a common use case for many users (e.g., #269, #272). I could help write this if it is helpful.

Best,
Jianyuan

**Comment by sarlinpe** [comment]
Hi Jianyuan,
This binding is actually available in COLMAP's main branch since https://github.com/colmap/colmap/commit/0ea2d5ceee1360bba427b2ef61f1351e59a46f91. If you need more fine-grained control over the BA setup, feel free to try https://github.com/colmap/colmap/pull/2509 and to leave comments if you have suggestions.

**Comment by jytime** [comment]
Hi thanks for the quick update! I will look at it :)
