### ISSUE TITLE
About the function pycolmap.triangulate_points

### ISSUE THREAD

**Issue by Jemian2023** [colmap/pycolmap#277]
When I run a command 
`pycolmap.triangulate_points(
                reference_model, database_path, image_dir, model_path, options=options
            )`
Are the map points triangulated only? Will the known camera intrinsic parameters and camera poses be optimized?
Looking forward to your answer!

**Comment by jytime** [comment]
I think so, as the source C++ code for pycolmap.triangulate_points seems to be this:

https://github.com/colmap/colmap/blob/dcfd14b300868c7eb1b360ebbca0dc21acd641b6/src/colmap/controllers/incremental_mapper.cc#L540

**Comment by sarlinpe** [comment]
Camera poses are always kept fixed, intrinsics are optimized only if `refine_intrinsics=True`.
https://github.com/colmap/colmap/blob/03556bb2cc941b58c3a4c244e5549e06c2f8117a/src/colmap/exe/sfm.cc#L446-L449
