### ISSUE TITLE
Segmentation fault for using pycolmap.estimate_triangulation

### ISSUE THREAD

**Issue by Abbsalehi** [colmap/pycolmap#284]
I need to triangulate three points using estimate_triangulation to determine their 3D coordinate (tri_pt3d), as mentioned in issue #269. However, I encountered an error (mentioned below). After obtaining the 3D coordinate, I also need to use bundle_adjustment to optimize it. I would greatly appreciate any assistance with this. I have uploaded the camera, 2D points, and image lists as a zip file to help replicate the error. Please let me know if you need additional information. I used Colmap to generate the reconstruction model and read the Colmap sparse model using Pycolmap.

OS: WSL-Ubuntu, CPU only

Please download the zip file here.
[files.zip](https://github.com/user-attachments/files/16418192/files.zip)

```python

#load camera, images, and 2D points
cams = np.load('cams.npy', allow_pickle=True)
imgs= np.load('imgs.npy', allow_pickle=True)
pts_2d= np.load('pts_2d.npy', allow_pickle=True)

# Create PointData instances for triangulation
tri_pts = [
    pycolmap.PointData(pt, cam.cam_from_img(pt))
    for pt, cam in zip(pts_2d, cams)
]

# Estimate the 3D point using triangulation
tri_pt3d = pycolmap.estimate_triangulation(tri_pts, imgs, cams)
```

The error:

```python
*** Aborted at 1722280885 (unix time) try "date -d @1722280885" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x20) received by PID 12150 (TID 0x7f5cf91c9600) from PID 32; stack trace: ***
    @     0x7f5c6d9c4dce (unknown)
    @     0x7f5cf920f320 (unknown)
    @           0x4e0a32 _PyObject_MakeTpCall
    @           0x4e7b62 object_vacall
    @           0x4e7821 PyObject_CallFunctionObjArgs
    @     0x7f5c6d8174bb (unknown)
    @     0x7f5c6d82cf6a (unknown)
    @     0x7f5c6d8bbb66 (unknown)
    @     0x7f5c6d81d761 (unknown)
    @           0x4f5412 PyCFunction_Call
    @           0x4e0cab _PyObject_MakeTpCall
    @           0x4dcd84 _PyEval_EvalFrameDefault
    @           0x4d6f41 _PyEval_EvalCodeWithName
    @           0x586749 PyEval_EvalCodeEx
    @           0x58670b PyEval_EvalCode
    @           0x58a851 builtin_exec
    @           0x4e8b8b cfunction_vectorcall_FASTCALL
    @           0x4d831b _PyEval_EvalFrameDefault
    @           0x4fc16b gen_send_ex
    @           0x4dcc5c _PyEval_EvalFrameDefault
    @           0x4fc16b gen_send_ex
    @           0x4dcc5c _PyEval_EvalFrameDefault
    @           0x4fc16b gen_send_ex
    @           0x4f37c5 method_vectorcall_O
    @           0x4d8632 _PyEval_EvalFrameDefault
    @           0x4e8036 _PyFunction_Vectorcall
    @           0x4d831b _PyEval_EvalFrameDefault
    @           0x4e8036 _PyFunction_Vectorcall
    @           0x4d8632 _PyEval_EvalFrameDefault
    @           0x4d6f41 _PyEval_EvalCodeWithName
    @           0x4f4f7b method_vectorcall
    @           0x4d90da _PyEval_EvalFrameDefault
/tmp/tmpzi0njgrx: line 3: 12150 Segmentation fault 
```

**Comment by Abbsalehi** [comment]
I just updated Pycolmap=0.6.0 to 3.10.0, it says:
```python
 pycolmap.PointData(pt, cam.cam_from_img(pt))
AttributeError: module 'pycolmap' has no attribute 'PointData'

**Comment by sarlinpe** [comment]
As mentioned in the README, the source code of pycolmap now lives in https://github.com/colmap/colmap. In 3.10.0, the interface of `pycolmap.estimate_triangulation` has been simplified: https://github.com/colmap/colmap/blob/03556bb2cc941b58c3a4c244e5549e06c2f8117a/src/pycolmap/estimators/triangulation.cc#L20-L24
The arguments are now:
- a list of 2D points
- a list of `pycolmap.Rigid3d`
- a list of `pycolmap.Camera`

**Comment by Abbsalehi** [comment]
> As mentioned in the README, the source code of pycolmap now lives in https://github.com/colmap/colmap. In 3.10.0, the interface of `pycolmap.estimate_triangulation` has been simplified: https://github.com/colmap/colmap/blob/03556bb2cc941b58c3a4c244e5549e06c2f8117a/src/pycolmap/estimators/triangulation.cc#L20-L24
> 
> The arguments are now:
> 
> - a list of 2D points
> 
> - a list of `pycolmap.Rigid3d`
> 
> - a list of `pycolmap.Camera`

@sarlinpe thanks for your response. I appreciate it if you can share an example to estimate triangulation and then do bundle adjustment.

**Comment by Abbsalehi** [comment]
I discovered the source of the error: the order of pts_2d was inconsistent with imgs.
