### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wolf943134497** [colmap/pycolmap#38]
>>> import pycolmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/anaconda3/envs/sfm/lib/python3.7/site-packages/pycolmap.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5ceres7Problem25SetParameterBlockConstantEPKd

any suggestions?

**Comment by johnwlambert** [comment]
Do you mind sharing your python and OS versions?

**Comment by wolf943134497** [comment]
> Do you mind sharing your python and OS versions?
