### ISSUE TITLE
Example for exporting model?

### ISSUE THREAD

**Issue by SuwoongHeo** [colmap/pycolmap#47]
Hi, 

I want to export the reconstruction to reconstruct the dense model from that. There are several options to export models into NVM, VRML, PLY, bundler as in  [reconstruction/reconstruction.cc](https://github.com/colmap/pycolmap/blob/0d1f63f5e5b2ce3ba0de39cc9d4297d3677777d4/reconstruction/reconstruction.cc). But the usages of these functions are unclear for me. Could you kindly provide an example of exporting models?

**Comment by Phil26AT** [comment]
Indeed the documentation of exporting pycolmap reconstructions was a bit sparse. We extended the export bindings and added some documentation in the README on branch [`export-reconstruction`](https://github.com/colmap/pycolmap/tree/export-reconstruction). Please let us know if this clarifies the usage of these functions.
