### ISSUE TITLE
installing in windows occured error

### ISSUE THREAD

**Issue by uzibuxing** [colmap/pycolmap#48]
Dear author,
Command line warning D9002: ignoring unknown option '-std=c++11'
when  I installed old pycolmap did not occur error

**Comment by uzibuxing** [comment]
Finally, I solved the problem but new one comes
CMake Warning:Manually-specified variables were not used by the project:VERSION_INFO

**Comment by sarlinpe** [comment]
We now have [instructions to build PyCOLMAP on Windows](https://github.com/colmap/pycolmap/tree/sarlinpe/windows-ci#building-from-source). We also have pre-built wheels that are available [here](https://github.com/colmap/pycolmap/actions/runs/7286946343) and can be installed with pip. I don't have a Windows machine at hand so it'd be great if someone could confirm that they work. We'll then release them on PyPI.
