### ISSUE TITLE
How to use GPS information in pycolmap

### ISSUE THREAD

**Issue by TNTSAYou** [colmap/pycolmap#53]
Hello, is there a function interface like model_aligner that uses GPS information to adjust the model in pycolmap? thanks for your help.

**Comment by Phil26AT** [comment]
Hi @TNTSAYou, you can use [`reconstruction.align(image_names, locations, min_common_images)`](https://github.com/colmap/pycolmap/blob/master/reconstruction/reconstruction.cc#L232-L235) or  [`reconstruction.align_robust(image_names, locations, min_common_images, max_error=12.0, min_inlier_ratio=0.1)`](https://github.com/colmap/pycolmap/blob/master/reconstruction/reconstruction.cc#L236-L242), which aligns the reconstruction to the gps-positions in-place and returns the transformation. `locations` should be a list of world coordinates `[x, y, z]` here.

**Comment by TNTSAYou** [comment]
@Phil26AT  Thanks for your help, I found this method, ready to apply to my dataset. Thanks again for your answer and the pycolmap project scheme.
