### ISSUE TITLE
Can pycolmap do dense reconstruction?

### ISSUE THREAD

**Issue by TNTSAYou** [colmap/pycolmap#54]
Sorry to bother you again, can pycolmap do dense reconstruction? I didn't find the interface inside.

**Comment by Skydes** [comment]
@Phil26AT has added support for MVS in the `cuda-bindings` branch. This requires COLMAP to be built with CUDA support:
https://github.com/colmap/pycolmap/blob/b30a4501b71364aa19adc990a401177c39a5ae62/pipeline/mvs.cc#L230-L247
Please let us know if you try it out!
