### ISSUE TITLE
Preventing focal length refinement

### ISSUE THREAD

**Issue by lucasestini** [colmap/pycolmap#55]
Hi, 

is it possible to prevent pycolmap from refining the focal length specified in the database during _incremental_mapping_? Using the GUI I would do that by deselecting _refine_focal_length_ 

Thanks!

**Comment by Skydes** [comment]
PR https://github.com/colmap/pycolmap/pull/56 adds support for [`IncrementalMapperOptions`](https://github.com/colmap/colmap/blob/33e26924f950172751f044a89b964129b3728db8/src/controllers/incremental_mapper.h#L41-L158), does this work for you?
```python
 incremental_mapping(
    database_path, images_path, output_path, dict(ba_refine_focal_length=False),
)
```

**Comment by lucasestini** [comment]
Hi,

great, thanks! In order to work with the updated version I need to build pycolmap from source, right? 
I'm working on a remote cluster with no root access, so I pip installed pycolmap, which avoided me to install COLMAP. Is there an alternative way to update it? 

Thanks!

**Comment by Skydes** [comment]
You can download the latest wheel from our CI: https://github.com/colmap/pycolmap/actions/runs/2017977100
Pick the right wheel, unzip, and `pip install file.whl`
