### ISSUE TITLE
Shared intrinsics for all cameras

### ISSUE THREAD

**Issue by Zhu-Liyuan** [colmap/pycolmap#61]
Hi, 

thank you for maintaining these great python wheels for colmap. I want to ask is there any place to set all the cameras to share the same intrinsics and I don't want colmap to adjust the image intrinsics one by one. 

There is a 'shared for all images' button in feature extraction in colmap gui. 

I extracted image features with superpoint(I used hloc) and can I set shared intrinsics for all images with pycolmap? 

Another question would be if I set 'shared intrinsics for all images', will colmap adjust the intrinsics of all images at the same time, one by one or just fix them during bundle adjustment?

Best regards,
Liyuan

**Comment by Phil26AT** [comment]
Yes, you can set shared intrinsics with camera_mode=[pycolmap.CameraMode.SINGLE](https://github.com/colmap/pycolmap/blob/master/pipeline/images.cc#L185-L190) in [hloc reconstruction](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/reconstruction.py#L79) or in [pycolmap.import_images](https://github.com/colmap/pycolmap/blob/master/pipeline/images.cc#L255-L262).

With shared intrinsics, COLMAP uses one camera for all images, and the intrinsics will be adjusted jointly during bundle adjustment.

**Comment by Zhu-Liyuan** [comment]
Thanks!

**Comment by aunagar** [comment]
Regarding shared / per image intrinsic. I see that we can set `CameraMode` SINGLE or PER_IMAGE. But where do we pass the known intrinsics? I see the option of adding [`camera_model`](https://github.com/colmap/pycolmap/blob/bc6eb0e73e9adbffc401cf99f89b7fa51fb17dd5/pipeline/images.cc#L255-L262), but not the actual intrinsic parameters in `insert_images` function.

**Comment by Skydes** [comment]
Indeed, `CameraMode` defines how the cameras are shared across images and `camera_model` defines the type of camera (pinhole, radial, etc.) but the focal length is always [inferred from the EXIF](https://github.com/colmap/colmap/blob/e180948665b03c4a12d45e2ca39a589f42fdbda6/src/util/bitmap.cc#L312-L313) (image size + sensor specs) while the distortion parameters are initialized to zero. 

To actually force a known camera, it is best to directly modify the database:
```python
from hlco.utils.database import COLMAPDatabase
db = COLMAPDatabase.connect(database_path)
cam_id = 0
cam_tuple = (cam.model_id, cam.width, cam.height, tuple(cam.params))
db.add_camera(*cam_tuple, camera_id=cam_id)
for i, name in enumerate(sorted(image_list)):
    db.add_image(name, cam_id, image_id=i+1)
db.commit()
db.close()
```

**Comment by zr19980402** [comment]
As the known camera intrinsic, some details to consult.
Firstly, "cam_tuple = (cam.model_id....) " If we should define a camera structure before the code
Secondly,  shoud the image_list be put into the  hloc function (import_images)

below are the codes.
![2](https://user-images.githubusercontent.com/81617596/173028689-dd968229-9056-4257-961b-6fb836ec9594.png)

details!
 import_images is the hloc function.

**Comment by zr19980402** [comment]
if you want to use fixed camera paremeters, you can download the pycolmap source codes. 
1. to change the images.cc  you will find it use the colmap as the base. so you can change the ImageOption (class).
2.  rebuild pycolmap & holc.
