### ISSUE TITLE
Feature Matching Support w/o Database

### ISSUE THREAD

**Issue by shreyas23** [colmap/pycolmap#63]
Are there any plans to support SIFT feature matching without creating a database file? Maybe through the SIFT interface?

**Comment by Skydes** [comment]
You can extract SIFT features with `pycolmap.Sift` (supports both CPU and GPU) and match them with [hloc's nearest neighbor matcher](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/matchers/nearest_neighbor.py) based on PyTorch. This is also trivial to implement with Numpy.
