### ISSUE TITLE
Input arguments for generalized_absolute_pose.cc 

### ISSUE THREAD

**Issue by Zhu-Liyuan** [colmap/pycolmap#69]
Hi pycolmap team,

thanks for maintaining this great project! I feel a bit unclear about the input arguments for rig_absolute_pose_estimation:
```
py::dict rig_absolute_pose_estimation(
        const std::vector<std::vector<Eigen::Vector2d>> points2D,
        const std::vector<std::vector<Eigen::Vector3d>> points3D,
        const std::vector<Camera> cameras,
        const std::vector<Eigen::Vector4d> rig_qvecs,
        const std::vector<Eigen::Vector3d> rig_tvecs,
        RANSACOptions ransac_options,
        AbsolutePoseRefinementOptions refinement_options,
        const bool return_covariance
) 
```
For `rig_qvecs` and `rig_tvecs`, I guess they should contain the camera poses inside the rig. I am not sure whether these poses should be in the local frame of the camera rig(for example, poses w.r.t. the center of the camera rig) or they should be in the same coordinate system of the `points3D`(I would call it world frame)? There's not too much comment in the code there so I can't figure it out confidently.

I also notice in colmap function [RefineGeneralizedAbsolutePose](https://github.com/colmap/colmap/blob/ac6bf11f15084039af8100735bd4bcde76b69668/src/estimators/pose.cc#L425) that you set the rig_poses to constant, meaning you are not changing the inner geometry or the rig. And should the output of rig_absolute_pose_estimation be the pose of the rig center(tvec, qvec)?

Regards,
Liyuan

**Comment by Skydes** [comment]
1. `rig_qvecs` and `rig_tvecs` are [the transformations from the rig frame to the individual cameras](https://github.com/colmap/colmap/blob/e180948665b03c4a12d45e2ca39a589f42fdbda6/src/estimators/generalized_relative_pose.h#L62-L64).
2. `RefineGeneralizedAbsolutePose` does not optimize the rig relative poses as they are likely under-constrained for a single instance.
3. The output of `rig_absolute_pose_estimation` is the transformation from the world frame to the rig frame.
