### ISSUE TITLE
Windows: failure for wheel building

### ISSUE THREAD

**Issue by zr19980402** [colmap/pycolmap#70]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing c:\dev\pycolmap-master
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [205 lines of output]
      running bdist_wheel
      running build
      running build_ext
      C:\dev\pycolmap-master\setup.py:29: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
      -- Using VCPKG FindLAPACK from package 'lapack-reference'
      -- A library with LAPACK API found.
      -- Found required Ceres dependency: Eigen version 3.4.0 in C:/dev/vcpkg/installed/x64-windows/share/eigen3
      -- Using VCPKG FindLAPACK from package 'lapack-reference'
      -- A library with LAPACK API found.
      -- Found Ceres version: 2.1.0 installed in: C:/dev/vcpkg/installed with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, Multithreading]
      CMake Warning at C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1384 (message):
        New Boost version may have incorrect or missing dependencies and imported
        targets
      Call Stack (most recent call first):
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:2117 (_Boost_MISSING_DEPENDENCIES)
        C:/dev/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:778 (include)
        C:/dev/vcpkg/installed/x64-windows/share/colmap/COLMAPConfig.cmake:94 (find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        CMakeLists.txt:4 (find_package)

      CMake Warning at C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1384 (message):
        New Boost version may have incorrect or missing dependencies and imported
        targets
      Call Stack (most recent call first):
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:2117 (_Boost_MISSING_DEPENDENCIES)
        C:/dev/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:778 (include)
        C:/dev/vcpkg/installed/x64-windows/share/colmap/COLMAPConfig.cmake:94 (find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        CMakeLists.txt:4 (find_package)

      CMake Warning at C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1384 (message):
        New Boost version may have incorrect or missing dependencies and imported
        targets
      Call Stack (most recent call first):
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:2117 (_Boost_MISSING_DEPENDENCIES)
        C:/dev/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:778 (include)
        C:/dev/vcpkg/installed/x64-windows/share/colmap/COLMAPConfig.cmake:94 (find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        CMakeLists.txt:4 (find_package)

      CMake Warning at C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1384 (message):
        New Boost version may have incorrect or missing dependencies and imported
        targets
      Call Stack (most recent call first):
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:1507 (_Boost_COMPONENT_DEPENDENCIES)
        C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FindBoost.cmake:2117 (_Boost_MISSING_DEPENDENCIES)
        C:/dev/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:778 (include)
        C:/dev/vcpkg/installed/x64-windows/share/colmap/COLMAPConfig.cmake:94 (find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        CMakeLists.txt:4 (find_package)

      -- Found Boost: C:/dev/vcpkg/installed/x64-windows/include (found version "1.79.0") found components: program_options filesystem system unit_test_framework
      -- Found Eigen
      --   Includes : C:/dev/vcpkg/installed/x64-windows/include/eigen3
      -- Found FreeImage
      --   Includes : C:/dev/vcpkg/installed/x64-windows/include
      --   Libraries : C:/dev/vcpkg/installed/x64-windows/lib/FreeImage.lib
      -- Found Metis
      --   Includes : C:/dev/vcpkg/installed/x64-windows/include
      --   Libraries : C:/dev/vcpkg/installed/x64-windows/debug/lib/metis.lib
      -- Found Glog
      --   Includes : C:/dev/vcpkg/installed/x64-windows/include
      --   Libraries : C:/dev/vcpkg/installed/x64-windows/debug/lib/glog.lib
      CMake Warning at C:/dev/vcpkg/installed/x64-windows/share/cgal/CGALConfig.cmake:92 (message):
        CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
        default value of CGAL::data_file_path()
      Call Stack (most recent call first):
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        C:/dev/vcpkg/installed/x64-windows/share/colmap/COLMAPConfig.cmake:200 (find_package)
        C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
        CMakeLists.txt:4 (find_package)

      -- Visual Leak Detector (VLD) is not found.
      -- Using header-only CGAL
      -- Targetting Visual Studio 16 2019
      -- Target build environment supports auto-linking
      -- Using VC toolset 142.
      -- Generator uses intermediate configuration directory: $(Configuration)
      -- Found Boost: C:/dev/vcpkg/installed/x64-windows/include (found suitable version "1.79.0", minimum required is "1.48")
      -- Boost include dirs: C:/dev/vcpkg/installed/x64-windows/include
      -- Boost libraries:
      -- pybind11 v2.6.2 dev1
      CMake Warning (dev) at C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
        Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
        Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      Call Stack (most recent call first):
        pybind11/CMakeLists.txt:91 (cmake_dependent_option)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      Compiling bindings without CUDA support.
      -- Configuring done
      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:

          CMAKE_TOOLCHAIN_FILE
……
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
      ['cmake', 'C:\\dev\\pycolmap-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\dev\\pycolmap-master\\build\\lib.win-amd64-cpython-38', '-DPYTHON_EXECUTABLE=D:\\Anaconda3\\python.exe', '-DVERSION_INFO=0.2.0', '-DCMAKE_TOOLCHAIN_FILE=C:\\dev\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\dev\\pycolmap-master\\build\\lib.win-amd64-cpython-38', '-DVCPKG_TARGET_TRIPLET=x64-windows', '-A', 'x64']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycolmap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by sarlinpe** [comment]
We now have [instructions to build PyCOLMAP on Windows](https://github.com/colmap/pycolmap/tree/sarlinpe/windows-ci#building-from-source). We also have pre-built wheels that are available [here](https://github.com/colmap/pycolmap/actions/runs/7286946343) and can be installed with pip. I don't have a Windows machine at hand so it'd be great if someone could confirm that they work. We'll then release them on PyPI.
