### ISSUE TITLE
how to add more images to a model

### ISSUE THREAD

**Issue by oldshuren1** [colmap/pycolmap#71]
After you add more images and matching features to the model's database. You can use colmap mapper --input_path model to create a new model with added images. Because it starts from an existing model, the process time usually is not very long. But pycolmap.incremental_mapping() won't take an existing model as the starting point. Is there another way to do it or should pycolmap.incremental_mapping() be modified to take an input model?

**Comment by sarlinpe** [comment]
This should now be support since https://github.com/colmap/pycolmap/commit/d2515968dfbabb47d33c5851ed9e1a93d8f1476c.
