### ISSUE TITLE
pycolmap & pycharm

### ISSUE THREAD

**Issue by zr19980402** [colmap/pycolmap#72]
i use pycharm to import pycolmap. but the __init__.py file has may errors. I don not know how to revise  it. 
![1](https://user-images.githubusercontent.com/81617596/173023115-d48c20b3-f0e5-4c9e-8ae3-c6b0fad9c2f5.png)
![2](https://user-images.githubusercontent.com/81617596/173023127-5c5721cd-8bb2-4112-bd30-0ccef92e44df.png)

**Comment by Skydes** [comment]
This is incorrect, `options` is a keyword argument:
https://github.com/colmap/pycolmap/blob/bc6eb0e73e9adbffc401cf99f89b7fa51fb17dd5/pipeline/sfm.cc#L182-L190
I don't use pycharm so I cannot help.

**Comment by zr19980402** [comment]
Thanks for your reply. Maybe it's the limitation of pycharm. In jupyter, is this import way  allowed? (from XXX[XXX]-the package name with []) and are this parameters' setting allowed?(def (xxx, yyy=yyy, zzz )  )the default parameter("options") is at the back of defined parameter (clean_points = true).
