### ISSUE TITLE
About calculation of essential matrix and fundamental matrix

### ISSUE THREAD

**Issue by AY1997** [colmap/pycolmap#75]
Hi, thank you for this excellent work. According to the definition of essential matrix and fundamental matrix, the calculation of the fundamental matrix requires camera intrinsics, which are not required by calculation of the essential matrix. But why is it the opposite in pycolmap's implementation?

Parameters:
- points2D1: Nx2 array; pixel coordinates in image 1
- points2D2: Nx2 array; pixel coordinates in image 2
- camera1: pycolmap.Camera of image 1
- camera2: pycolmap.Camera of image 2
Optional parameters:
- max_error_px: float; RANSAC inlier threshold in pixels (default=4.0)
- options: dict or pycolmap.RANSACOptions

**answer = pycolmap.essential_matrix_estimation(points2D1, points2D2, camera1, camera2)**

Returns: dictionary of estimation outputs

**answer = pycolmap.fundamental_matrix_estimation(
    points2D1,
    points2D2,
    [max_error_px],  # optional RANSAC inlier threshold in pixels
    [options],       # optional dict or pycolmap.RANSACOptions
)**

**Comment by Skydes** [comment]
No, you got it mixed up - computing E requires the camera intrinsics (normalized point coordinates) while computing F doesn't (pixel point coordinates).
https://en.wikipedia.org/wiki/Fundamental_matrix_(computer_vision)
