### ISSUE TITLE
pycolmap.absolute_pose_estimation() - Does it matter if 3D points are in world or camera space ?

### ISSUE THREAD

**Issue by alexs7** [colmap/pycolmap#83]
Hello,

Thanks for pycolmap !! Great work!

I think this is a more general/high-level question, it is about `pycolmap.absolute_pose_estimation()`

It says that the method assumes 3D points in world coordinates.

Assuming I have two sets of 2D-3D points correspondences:

- Set 1: The 3D points are in camera space (camera coordinate space)
- Set 2: The 3D points are in world space (world coordinate space)

For both sets the 2D points are the same.

For set 1, `pycolmap.absolute_pose_estimation()` will return a camera pose in camera space ?
For set 2, `pycolmap.absolute_pose_estimation()` will return a camera pose in world space ?

**Comment by mihaidusmanu** [comment]
I am not sure I understand the question. If the 3D points are in "camera coordinate space" then the pose of the camera is by definition identity (I_{4x4}) so there's nothing to estimate.

**Comment by alexs7** [comment]
@mihaidusmanu, For example in COLMAP, 3D points are given in world space coordinates. Camera poses are in camera space. What I mean is that if I multiply the 3D world points with a COLMAP camera pose, then I will get a list of transformed 3D points in camera space. Then in that space if I use the 2D - 3D (i.e the transformed ones) and run the ```pycolmap.absolute_pose_estimation()``` that should the identity matrix ? (I was mistaken to think that I will get the camera pose here)

**Comment by mihaidusmanu** [comment]
Camera space is defined as the space where your camera is axis-aligned and placed at the origin. So yes, you will get identity if you try to estimate a pose in its own coordinate frame.

If there are multiple cameras in the scene and you transform the points to one of them, e.g., C_1 and try to estimate the pose for another camera C_2, then you will get the relative pose between them.

**Comment by alexs7** [comment]
@mihaidusmanu,  Ok this helps a lot! Especially your second point. If I got it right, If I transform 3D points in two different camera spaces, C1, and C2, then running ```pycolmap.absolute_pose_estimation()```, between 2D_c1 - 3D_c1 should give me the `I` matrix, but 2D_c1 - 3D_c2 (i.e 2D points from camera 1 to 3D points from camera 2 space) should return the relative pose between C1 and C2 ? (Just getting my head around coordinate systems)

**Comment by mihaidusmanu** [comment]
Yes, that's correct.

**Comment by alexs7** [comment]
Thanks!

**Comment by alexs7** [comment]
@mihaidusmanu I was just wondering what is the points are not in camera space but just in world coordinates. And I follow the same ? In that case I won't get a relative pose as a result but just an arbitary camera world pose ?
