### ISSUE TITLE
module 'pycolmap' has no attribute 'Reconstruction'

### ISSUE THREAD

**Issue by nuggy875** [colmap/pycolmap#86]
Thank you for your useful library..
From an unkwown time, Reconstruction function have some error..

<img width="729" alt="image" src="https://user-images.githubusercontent.com/20698215/186353687-e080ba19-deaf-4433-9f6e-8f4a3bd2e2cf.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/20698215/186353713-1ab97a99-2e0e-48aa-ba77-9a9aadc43828.png">

Could you tell me what is wrong?

I'm in ubuntu 20.04.

**Comment by mihaidusmanu** [comment]
I cannot reproduce this issue on my end. Are you using the latest version of pycolmap? What's the output of `import pycolmap; print(pycolmap.__version__)`? What version of python are you on?

**Comment by nuggy875** [comment]
my bad.. maybe some python import problem.
