### ISSUE TITLE
Missing mask path in ImageReaderOptions

### ISSUE THREAD

**Issue by DamodarNayak9398** [colmap/pycolmap#90]
Hi, 
I wanted to provide mask path for feature extraction, but there was no option for it in ImageReaderOptions. However camera_mask_path was defined not sure how different it is from mask_path since I am used to using mask_path in colmap. 
Also wanted to point out that max_num_features is defined twice in SiftExtractionOptions. 
Thank you in advance for the help

**Comment by Phil26AT** [comment]
Hi @DamodarNayak9398,

thanks for pointing this out. I have pushed changes to the branch [`image-reader`](https://github.com/colmap/pycolmap/tree/image-reader) that adds mask_path to the ImageReaderOptions. Please let me know if this works for you as intended, and we will include this in the next release.

**Comment by DamodarNayak9398** [comment]
@Phil26AT Thank you for the prompt reply, it works however while installing, it threw an error because the pybind help for mask_path does not have "" for every line. Once I added "" for every line it worked.

**Comment by DamodarNayak9398** [comment]
I have one more question, I work with video frames and for the registration to work I need to tweek the init_min_tri_angle parameter of the incremental mapper which is not supported yet I believe, is it under development?

**Comment by DamodarNayak9398** [comment]
Sounds good. Thank you for the help
