### ISSUE TITLE
Sparse reconstruction with GPU

### ISSUE THREAD

**Issue by ajuric** [colmap/pycolmap#97]
After reading [this MR](https://github.com/colmap/pycolmap/pull/57), I understand that I need to build COLMAP manually to have CUDA support, and that I will be able to use CUDA in feature extraction and matching.

But I'm not sure if CUDA can be utilized also in sparse reconstruction? From what is see during the execution, CUDA is not utilized during the sparse reconstruction?

**Comment by Phil26AT** [comment]
No, sparse reconstruction does not use CUDA, but MVS does. However, ceres starting from v2.1.0 supports CUDA for dense matrix factorizations, and could be used for small bundle adjustment problems.

**Comment by evan-wes** [comment]
@Phil26AT is there any plan to include CUDA support for sparse reconstruction?
